In [1]:
import pandas as pd
data={
    'Product':['Laptop','Phone','Chair','Table','Headphones','Monitor'],
    'Category':['Electronics','Electronics','Furniture','Furniture','Electronics','Electronics'],
    'Price':[800,400,75,150,50,200],
    'Quantity':[3,5,10,4,12,6]
    }
df=pd.DataFrame(data) 
df

      Product     Category  Price  Quantity
0      Laptop  Electronics    800         3
1       Phone  Electronics    400         5
2       Chair    Furniture     75        10
3       Table    Furniture    150         4
4  Headphones  Electronics     50        12
5     Monitor  Electronics    200         6

In [3]:
df['Sales']=df['Price']*df['Quantity']
sales_df=df
sales_df

      Product     Category  Price  Quantity  Sales
0      Laptop  Electronics    800         3   2400
1       Phone  Electronics    400         5   2000
2       Chair    Furniture     75        10    750
3       Table    Furniture    150         4    600
4  Headphones  Electronics     50        12    600
5     Monitor  Electronics    200         6   1200

In [5]:
sales_df.to_csv('sales_analysis.csv',index=False)

In [8]:
sales_df=pd.read_csv('sales_analysis.csv') 
sales_df

      Product     Category  Price  Quantity  Sales
0      Laptop  Electronics    800         3   2400
1       Phone  Electronics    400         5   2000
2       Chair    Furniture     75        10    750
3       Table    Furniture    150         4    600
4  Headphones  Electronics     50        12    600
5     Monitor  Electronics    200         6   1200

In [10]:
#Display the first three rows
sales_df.head(3)

  Product     Category  Price  Quantity  Sales
0  Laptop  Electronics    800         3   2400
1   Phone  Electronics    400         5   2000
2   Chair    Furniture     75        10    750

In [11]:
#Display the last two rows
sales_df.tail(2)

      Product     Category  Price  Quantity  Sales
4  Headphones  Electronics     50        12    600
5     Monitor  Electronics    200         6   1200

In [12]:
#Find the number of rows and columns
sales_df.shape

(6, 5)

In [18]:
#Display the column names
sales_df.columns

Index(['Product', 'Category', 'Price', 'Quantity', 'Sales'], dtype='str')

In [19]:
#Use "info()" to inspect data types
sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Product   6 non-null      str
 1   Category  6 non-null      str
 2   Price     6 non-null      int64
 3   Quantity  6 non-null      int64
 4   Sales     6 non-null      int64
dtypes: int64(3), str(2)
memory usage: 372.0 bytes

In [20]:
#Use "describe()" to summarize numerical columns
sales_df.describe()

            Price   Quantity        Sales
count    6.000000   6.000000     6.000000
mean   279.166667   6.666667  1258.333333
std    283.908729   3.559026   772.280174
min     50.000000   3.000000   600.000000
25%     93.750000   4.250000   637.500000
50%    175.000000   5.500000   975.000000
75%    350.000000   9.000000  1800.000000
max    800.000000  12.000000  2400.000000

In [21]:
#Exercise 2: Filter the data
#Write code to find:

#Products costing less than 100.
cheaper_products=sales_df[sales_df['Price']<100]
print(cheaper_products)

      Product     Category  Price  Quantity  Sales
2       Chair    Furniture     75        10    750
4  Headphones  Electronics     50        12    600

In [23]:
#Products with a quantity greater than five
high_volume_pdts=sales_df[sales_df['Quantity']>5]
print(high_volume_pdts)

      Product     Category  Price  Quantity  Sales
2       Chair    Furniture     75        10    750
4  Headphones  Electronics     50        12    600
5     Monitor  Electronics    200         6   1200

In [24]:
#Products in the Furniture category
furniture_goods=sales_df[sales_df["Category"]=="Furniture"]
print(furniture_goods)

  Product   Category  Price  Quantity  Sales
2   Chair  Furniture     75        10    750
3   Table  Furniture    150         4    600

In [25]:
#Electronics products costing more than 100
expensive_electronics=sales_df[(sales_df['Category']=='Electronics')&(sales_df['Price']>100)]
print(expensive_electronics)

   Product     Category  Price  Quantity  Sales
0   Laptop  Electronics    800         3   2400
1    Phone  Electronics    400         5   2000
5  Monitor  Electronics    200         6   1200

In [26]:
#Exercise 3: Sales calculations
#Create the "Sales_Value" column
df['sales_value']=sales_df['Sales']
df

      Product     Category  Price  Quantity  Sales  sales_value
0      Laptop  Electronics    800         3   2400         2400
1       Phone  Electronics    400         5   2000         2000
2       Chair    Furniture     75        10    750          750
3       Table    Furniture    150         4    600          600
4  Headphones  Electronics     50        12    600          600
5     Monitor  Electronics    200         6   1200         1200

In [27]:
#Calculate the total sales value
print(df['sales_value'].sum())

7550

In [32]:
#Find the product with the highest sales value
highest_sold_product=df.loc[df['sales_value'].idxmax()]
print(highest_sold_product)

Product             Laptop
Category       Electronics
Price                  800
Quantity                 3
Sales                 2400
sales_value           2400
Name: 0, dtype: object

In [34]:
#Sort the products by sales value, from highest to lowest
print(df.sort_values('sales_value',ascending=False))

      Product     Category  Price  Quantity  Sales  sales_value
0      Laptop  Electronics    800         3   2400         2400
1       Phone  Electronics    400         5   2000         2000
5     Monitor  Electronics    200         6   1200         1200
2       Chair    Furniture     75        10    750          750
3       Table    Furniture    150         4    600          600
4  Headphones  Electronics     50        12    600          600

In [35]:
#Save the updated DataFrame as "analyzed_sales.csv"
df.to_csv('analyzed_sales.csv',index=False)

In [38]:
data = {
    "Name": ["Alice", "Brian", "Carol", "David"],
    "Age": [25, None, 30, 28],
    "Salary": [40000, 45000, None, 50000]
}
employees=pd.DataFrame(data)
employees

    Name   Age   Salary
0  Alice  25.0  40000.0
1  Brian   NaN  45000.0
2  Carol  30.0      NaN
3  David  28.0  50000.0

In [39]:
#Count missing values in each column
employees.isnull().sum()

Name      0
Age       1
Salary    1
dtype: int64

In [40]:
#Check whether any values are missing
employees.isnull()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False

In [41]:
#Remove rows containing missing values
employees=employees.dropna()
employees

    Name   Age   Salary
0  Alice  25.0  40000.0
3  David  28.0  50000.0

In [42]:
#Find the median age
employees['Age'].median()

np.float64(26.5)

In [45]:
#Fill the missing age with the median
employees=employees['Age'].fillna(employees['Age'].median())
employees

0    25.0
3    28.0
Name: Age, dtype: float64

In [46]:
data = {
    "Name": ["Alice", "Brian", "Carol", "David"],
    "Age": [25, None, 30, 28],
    "Salary": [40000, 45000, None, 50000]
}
employees=pd.DataFrame(data)
employees

    Name   Age   Salary
0  Alice  25.0  40000.0
1  Brian   NaN  45000.0
2  Carol  30.0      NaN
3  David  28.0  50000.0

In [47]:
employee['Age'].median()

np.float64(28.0)

In [51]:
employees['Age']=employees['Age'].fillna(employees['Age'].median())
employees

    Name   Age   Salary
0  Alice  25.0  40000.0
1  Brian  28.0  45000.0
2  Carol  30.0      NaN
3  David  28.0  50000.0

In [52]:
#Check whether any missing values remain
employee.isnull()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False

In [54]:
#Mini project: Shop Sales Data Analyst

#You are a junior data analyst working for a retail shop.

#Your manager provides a CSV file containing product names, categories, prices and quantities.

#Your task is to create a simple analysis report.

#Task 1: Load the data
Salez_df=pd.read_csv('sales_analysis.csv')
Salez_df

      Product     Category  Price  Quantity  Sales
0      Laptop  Electronics    800         3   2400
1       Phone  Electronics    400         5   2000
2       Chair    Furniture     75        10    750
3       Table    Furniture    150         4    600
4  Headphones  Electronics     50        12    600
5     Monitor  Electronics    200         6   1200

In [56]:
#Task 2: Inspect the data
#Total number of products
Salez_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Product   6 non-null      str
 1   Category  6 non-null      str
 2   Price     6 non-null      int64
 3   Quantity  6 non-null      int64
 4   Sales     6 non-null      int64
dtypes: int64(3), str(2)
memory usage: 372.0 bytes

In [58]:
#- Number of columns
Salez_df.columns

Index(['Product', 'Category', 'Price', 'Quantity', 'Sales'], dtype='str')

In [ ]:
#- Column names

In [60]:
#- Data types
Salez_df.dtypes

Product       str
Category      str
Price       int64
Quantity    int64
Sales       int64
dtype: object

In [61]:
#- Numerical summaries
Salez_df.describe()

            Price   Quantity        Sales
count    6.000000   6.000000     6.000000
mean   279.166667   6.666667  1258.333333
std    283.908729   3.559026   772.280174
min     50.000000   3.000000   600.000000
25%     93.750000   4.250000   637.500000
50%    175.000000   5.500000   975.000000
75%    350.000000   9.000000  1800.000000
max    800.000000  12.000000  2400.000000

In [72]:
#Task 3: Calculate sales

#Create a "Sales_Value" column.
df['Sales_Value']=Salez_df['Sales'] 
Sales_analysed_df=df
Sales_analysed_df

      Product     Category  Price  Quantity  Sales  Sales_Value
0      Laptop  Electronics    800         3   2400         2400
1       Phone  Electronics    400         5   2000         2000
2       Chair    Furniture     75        10    750          750
3       Table    Furniture    150         4    600          600
4  Headphones  Electronics     50        12    600          600
5     Monitor  Electronics    200         6   1200         1200

In [69]:
##Calculate total sales value and average sales value per product record.
df['Sales_Value'].sum()

np.int64(7550)

In [70]:
df['Sales_Value'].mean()

np.float64(1258.3333333333333)

In [74]:
#Task 4: Investigate the products

#Find The most expensive product
most_expensive=Sales_analysed_df.loc[Sales_analysed_df ['Price'].idxmax()] 
print(most_expensive)

Product             Laptop
Category       Electronics
Price                  800
Quantity                 3
Sales                 2400
Sales_Value           2400
Name: 0, dtype: object

In [75]:
#The product with the highest quantity
most_sold_product=Sales_analysed_df.loc[Sales_analysed_df['Quantity'].idxmax()]
print(most_sold_product)

Product         Headphones
Category       Electronics
Price                   50
Quantity                12
Sales                  600
Sales_Value            600
Name: 4, dtype: object

In [77]:
#The product with the highest sales value
Highest_value_product=Sales_analysed_df.loc[Sales_analysed_df['Sales_Value'].idxmax()]
print(Highest_value_product)

Product             Laptop
Category       Electronics
Price                  800
Quantity                 3
Sales                 2400
Sales_Value           2400
Name: 0, dtype: object

In [79]:
#All Electronics products
All_Electronics=Sales_analysed_df[Sales_analysed_df['Category']=='Electronics']
print(All_Electronics)

      Product     Category  Price  Quantity  Sales  Sales_Value
0      Laptop  Electronics    800         3   2400         2400
1       Phone  Electronics    400         5   2000         2000
4  Headphones  Electronics     50        12    600          600
5     Monitor  Electronics    200         6   1200         1200

In [80]:
#All products costing more than 150
High_priced_products=Sales_analysed_df[Sales_analysed_df['Price']>150]
print(High_priced_products)

   Product     Category  Price  Quantity  Sales  Sales_Value
0   Laptop  Electronics    800         3   2400         2400
1    Phone  Electronics    400         5   2000         2000
5  Monitor  Electronics    200         6   1200         1200

In [84]:
#Save the final DataFrame
Sales_analysed_df.to_csv("shop_sales_analysis.csv",index=False)

In [86]:
Sales_analysed=pd.read_csv("shop_sales_analysis.csv") 
Sales_analysed

      Product     Category  Price  Quantity  Sales  Sales_Value
0      Laptop  Electronics    800         3   2400         2400
1       Phone  Electronics    400         5   2000         2000
2       Chair    Furniture     75        10    750          750
3       Table    Furniture    150         4    600          600
4  Headphones  Electronics     50        12    600          600
5     Monitor  Electronics    200         6   1200         1200

In [89]:
#Homework

#Part A: Employee dataset

#Create and save this dataset:

data={
    "Name": ["John", "Mary", "Peter", "Jane", "David"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales" ],
    "Age": [25, 31, 28, 35, 29],
    "Salary": [45000, 52000, 48000, 65000, 50000]
}
employees=pd.DataFrame(data)
employees

    Name Department  Age  Salary
0   John         IT   25   45000
1   Mary         HR   31   52000
2  Peter    Finance   28   48000
3   Jane         IT   35   65000
4  David      Sales   29   50000

In [94]:
employees.to_csv('employees_data.csv',index=False)

In [95]:
#Load "employees.csv" into a new DataFrame
employees_df=pd.read_csv('employees_data.csv')
employees_df

    Name Department  Age  Salary
0   John         IT   25   45000
1   Mary         HR   31   52000
2  Peter    Finance   28   48000
3   Jane         IT   35   65000
4  David      Sales   29   50000

In [96]:
#Display the first three rows
employees_df.head(3)

    Name Department  Age  Salary
0   John         IT   25   45000
1   Mary         HR   31   52000
2  Peter    Finance   28   48000

In [97]:
#Find the number of rows and columns
employees_df.shape

(5, 4)

In [101]:
# Display the column names and data types
employees_df.columns 
employees_df.dtypes

Name            str
Department      str
Age           int64
Salary        int64
dtype: object

In [104]:
#Calculate the average salary
print(employees_df["Salary"].mean())

52000.0

In [105]:
# Find employees earning more than 50,000
High_earners=employees_df.loc[employees_df["Salary"]>50000]
print(High_earners)

   Name Department  Age  Salary
1  Mary         HR   31   52000
3  Jane         IT   35   65000

In [106]:
#Find employees working in IT
IT_employees=employees_df.loc[employees_df["Department"]=="IT"]
print(IT_employees)

   Name Department  Age  Salary
0  John         IT   25   45000
3  Jane         IT   35   65000

In [108]:
#Sort employees by salary from highest to lowest
print(employees_df.sort_values("Salary",ascending=False))

    Name Department  Age  Salary
3   Jane         IT   35   65000
1   Mary         HR   31   52000
4  David      Sales   29   50000
2  Peter    Finance   28   48000
0   John         IT   25   45000

In [ ]:
#Save the results as "employees_analysis.csv"

In [111]:
#Create a new column called "Annual_Bonus" equal to 5% of salary
employees_df["Annual_Bonus"]=employees_df["Salary"]*0.05
employees_df

    Name Department  Age  Salary  Annual_Bonus
0   John         IT   25   45000        2250.0
1   Mary         HR   31   52000        2600.0
2  Peter    Finance   28   48000        2400.0
3   Jane         IT   35   65000        3250.0
4  David      Sales   29   50000        2500.0

In [112]:
#Total_Compensation
employees_df['Total_compensation']=employees_df['Salary']+employees_df['Annual_Bonus'] 
employees_df

    Name Department  Age  Salary  Annual_Bonus  Total_compensation
0   John         IT   25   45000        2250.0             47250.0
1   Mary         HR   31   52000        2600.0             54600.0
2  Peter    Finance   28   48000        2400.0             50400.0
3   Jane         IT   35   65000        3250.0             68250.0
4  David      Sales   29   50000        2500.0             52500.0