In [1]:
import pandas as pd

In [2]:
#Create a sample employee dataset:

data = {
    "Name": ["Alice", "Brian", "Carol", "David","Eva", "Frank", "Grace", "Henry","Irene", "James" ],
    "Age": [25, 32, 28, 41, 35, 29, 38, 24, 45, 31],
    "Department": ["IT", "Finance", "IT", "HR", "Sales","Finance", "IT", "Sales", "HR", "IT"],
    "Salary": [45000, 65000, 52000, 72000, 58000,49000, 85000, 40000, 78000, 61000],
    "Performance": [85, 78, 92, 74, 88, 81, 95, 70, 90, 86]
}
df=pd.DataFrame(data) 
df

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
1  Brian   32    Finance   65000           78
2  Carol   28         IT   52000           92
3  David   41         HR   72000           74
4    Eva   35      Sales   58000           88
5  Frank   29    Finance   49000           81
6  Grace   38         IT   85000           95
7  Henry   24      Sales   40000           70
8  Irene   45         HR   78000           90
9  James   31         IT   61000           86

In [3]:
#4. Selecting One Column

#To select the employee names
df["Name"]

0    Alice
1    Brian
2    Carol
3    David
4      Eva
5    Frank
6    Grace
7    Henry
8    Irene
9    James
Name: Name, dtype: str

In [4]:
#selecting multiple columns
df[["Name","Department","Salary"]]

    Name Department  Salary
0  Alice         IT   45000
1  Brian    Finance   65000
2  Carol         IT   52000
3  David         HR   72000
4    Eva      Sales   58000
5  Frank    Finance   49000
6  Grace         IT   85000
7  Henry      Sales   40000
8  Irene         HR   78000
9  James         IT   61000

In [7]:
#Practice-Display only:

#1. Names and ages.

df[["Name","Age"]]

    Name  Age
0  Alice   25
1  Brian   32
2  Carol   28
3  David   41
4    Eva   35
5  Frank   29
6  Grace   38
7  Henry   24
8  Irene   45
9  James   31

In [8]:
#2. Names and performance scores.
df[["Name","Performance"]]

    Name  Performance
0  Alice           85
1  Brian           78
2  Carol           92
3  David           74
4    Eva           88
5  Frank           81
6  Grace           95
7  Henry           70
8  Irene           90
9  James           86

In [10]:
#3. Departments and salaries.
df[["Department","Salary"]]

  Department  Salary
0         IT   45000
1    Finance   65000
2         IT   52000
3         HR   72000
4      Sales   58000
5    Finance   49000
6         IT   85000
7      Sales   40000
8         HR   78000
9         IT   61000

In [11]:
#5. Selecting Rows with "iloc"
#The "iloc" method selects records using numerical positions.Remember that Python indexing starts at zero.

#Select the first row

df.iloc[0]

Name           Alice
Age               25
Department        IT
Salary         45000
Performance       85
Name: 0, dtype: object

In [12]:
#Select the third row
df.iloc[2]

Name           Carol
Age               28
Department        IT
Salary         52000
Performance       92
Name: 2, dtype: object

In [13]:
#Select the first five rows
df.iloc[0:5]

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
1  Brian   32    Finance   65000           78
2  Carol   28         IT   52000           92
3  David   41         HR   72000           74
4    Eva   35      Sales   58000           88

In [15]:
#Select specific rows
df.iloc[[0,3,5]]

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
3  David   41         HR   72000           74
5  Frank   29    Finance   49000           81

In [16]:
#Selecting particular rows and columns

df.iloc[0:3, 0:2] 

#This selects:

#- Rows at positions 0, 1, and 2.
#- Columns at positions 0 and 1.

    Name  Age
0  Alice   25
1  Brian   32
2  Carol   28

In [17]:
#Selecting Data with "loc"
#The "loc" method selects data using index labels and column names.

#For example:

df.loc[0]

#Select the name and salary from row 0:

df.loc[0, ["Name", "Salary"]]

Name      Alice
Salary    45000
Name: 0, dtype: object

In [19]:
#Select rows 0 through 3
df.loc[0:3]

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
1  Brian   32    Finance   65000           78
2  Carol   28         IT   52000           92
3  David   41         HR   72000           74

In [24]:
#Filtering with Comparison Operators
df[df["Salary"]>60000]

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
3  David   41         HR   72000           74
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90
9  James   31         IT   61000           86

In [25]:
df[df["Salary"]<60000]

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
2  Carol   28         IT   52000           92
4    Eva   35      Sales   58000           88
5  Frank   29    Finance   49000           81
7  Henry   24      Sales   40000           70

In [26]:
#Example 3: Employees aged 30 or older
df[df["Age"]>=30]

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
3  David   41         HR   72000           74
4    Eva   35      Sales   58000           88
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90
9  James   31         IT   61000           86

In [27]:
#Example 4: Employees with performance scores below 80
df[df["Performance"]<80]

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
3  David   41         HR   72000           74
7  Henry   24      Sales   40000           70

In [28]:
#Example 5: Employees in IT
df[df["Department"]=="IT"]

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
2  Carol   28         IT   52000           92
6  Grace   38         IT   85000           95
9  James   31         IT   61000           86

In [30]:
#Example 6: Employees not in IT
df[df["Department"]!="IT"]

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
3  David   41         HR   72000           74
4    Eva   35      Sales   58000           88
5  Frank   29    Finance   49000           81
7  Henry   24      Sales   40000           70
8  Irene   45         HR   78000           90

In [35]:
#8. Filtering with Multiple Conditions
#Find employees who work in IT and earn more than 60,000
df[(df["Department"]=="IT") & (df["Salary"]>60000)]

    Name  Age Department  Salary  Performance
6  Grace   38         IT   85000           95
9  James   31         IT   61000           86

In [36]:
#Example 2: Employees older than 30 and earning at least 60,000
df[(df["Age"]>30) & (df["Salary"]>=60000)]

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
3  David   41         HR   72000           74
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90
9  James   31         IT   61000           86

In [37]:
#Example 3: Employees with performance scores of at least 90 and salaries above 50,000
df[(df["Performance"]>=90) & (df["Salary"]>50000)]

    Name  Age Department  Salary  Performance
2  Carol   28         IT   52000           92
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90

In [38]:
#9. Using OR Conditions

#Use "|" when at least one condition must be true.

#Example:«Find employees who work in IT or Finance.»
df[(df["Department"]=="IT") | (df["Department"]=="Finance")]

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
1  Brian   32    Finance   65000           78
2  Carol   28         IT   52000           92
5  Frank   29    Finance   49000           81
6  Grace   38         IT   85000           95
9  James   31         IT   61000           86

In [39]:
#«Find employees who earn more than 70,000 or have a performance score of at least 90.»
df[(df["Salary"]>70000) | (df["Performance"]>=90)]

    Name  Age Department  Salary  Performance
2  Carol   28         IT   52000           92
3  David   41         HR   72000           74
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90

In [40]:
#10. Excluding Records with "~". The "~" operator reverses a Boolean condition.
#For example, select employees who are not in IT:
df[~(df["Department"]=="IT")]

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
3  David   41         HR   72000           74
4    Eva   35      Sales   58000           88
5  Frank   29    Finance   49000           81
7  Henry   24      Sales   40000           70
8  Irene   45         HR   78000           90

In [41]:
#You can also exclude a set of departments:

df[~df["Department"].isin(["IT", "HR"])]

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
4    Eva   35      Sales   58000           88
5  Frank   29    Finance   49000           81
7  Henry   24      Sales   40000           70

In [42]:
df[df["Department"].isin(["IT", "Finance", "Sales"])]

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
1  Brian   32    Finance   65000           78
2  Carol   28         IT   52000           92
4    Eva   35      Sales   58000           88
5  Frank   29    Finance   49000           81
6  Grace   38         IT   85000           95
7  Henry   24      Sales   40000           70
9  James   31         IT   61000           86

In [46]:
#Find employees belonging to:

#1. IT or HR.
df[df["Department"].isin(["IT","HR"])]

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
2  Carol   28         IT   52000           92
3  David   41         HR   72000           74
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90
9  James   31         IT   61000           86

In [44]:
#2. Finance or Sales.
df[df["Department"].isin(["Finance","Sales"])]

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
4    Eva   35      Sales   58000           88
5  Frank   29    Finance   49000           81
7  Henry   24      Sales   40000           70

In [45]:
#3. IT, HR, or Finance.
df[df["Department"].isin(["IT","HR","Finance"])]

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
1  Brian   32    Finance   65000           78
2  Carol   28         IT   52000           92
3  David   41         HR   72000           74
5  Frank   29    Finance   49000           81
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90
9  James   31         IT   61000           86

In [48]:
#12. Filtering a Range with "between()"
#Find employees earning between 50,000 and 70,000:
df[df["Salary"].between(50000,70000)]

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
2  Carol   28         IT   52000           92
4    Eva   35      Sales   58000           88
9  James   31         IT   61000           86

In [49]:
#Find employees aged between 25 and 35:
df[df["Age"].between(25,30)]

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
2  Carol   28         IT   52000           92
5  Frank   29    Finance   49000           81

In [50]:
#Find employees whose performance scores are between 80 and 90:
df[df["Performance"].between(80,90)]

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
4    Eva   35      Sales   58000           88
5  Frank   29    Finance   49000           81
8  Irene   45         HR   78000           90
9  James   31         IT   61000           86

In [51]:
#Filtering with "query()"
df.query("Salary > 60000")

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
3  David   41         HR   72000           74
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90
9  James   31         IT   61000           86

In [52]:
#Find employees who are older than 30 and earn more than 60,000:
df.query("Age>30" and "Salary>60000")

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
3  David   41         HR   72000           74
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90
9  James   31         IT   61000           86

In [55]:
#Find employees from IT:
df.query("Department=='IT'")

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
2  Carol   28         IT   52000           92
6  Grace   38         IT   85000           95
9  James   31         IT   61000           86

In [56]:
#Find employees whose performance is at least 90:
df.query("Performance>=90")

    Name  Age Department  Salary  Performance
2  Carol   28         IT   52000           92
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90

In [57]:
#14. Sorting Data
#Sorting arranges records by one or more columns.

#Sort salaries from lowest to highest
df.sort_values(["Salary"])

    Name  Age Department  Salary  Performance
7  Henry   24      Sales   40000           70
0  Alice   25         IT   45000           85
5  Frank   29    Finance   49000           81
2  Carol   28         IT   52000           92
4    Eva   35      Sales   58000           88
9  James   31         IT   61000           86
1  Brian   32    Finance   65000           78
3  David   41         HR   72000           74
8  Irene   45         HR   78000           90
6  Grace   38         IT   85000           95

In [59]:
df.sort_values(["Salary"],ascending=False)

    Name  Age Department  Salary  Performance
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90
3  David   41         HR   72000           74
1  Brian   32    Finance   65000           78
9  James   31         IT   61000           86
4    Eva   35      Sales   58000           88
2  Carol   28         IT   52000           92
5  Frank   29    Finance   49000           81
0  Alice   25         IT   45000           85
7  Henry   24      Sales   40000           70

In [61]:
#Sort employees by age
df.sort_values("Age")

    Name  Age Department  Salary  Performance
7  Henry   24      Sales   40000           70
0  Alice   25         IT   45000           85
2  Carol   28         IT   52000           92
5  Frank   29    Finance   49000           81
9  James   31         IT   61000           86
1  Brian   32    Finance   65000           78
4    Eva   35      Sales   58000           88
6  Grace   38         IT   85000           95
3  David   41         HR   72000           74
8  Irene   45         HR   78000           90

In [62]:
df.sort_values("Age",ascending=False)

    Name  Age Department  Salary  Performance
8  Irene   45         HR   78000           90
3  David   41         HR   72000           74
6  Grace   38         IT   85000           95
4    Eva   35      Sales   58000           88
1  Brian   32    Finance   65000           78
9  James   31         IT   61000           86
5  Frank   29    Finance   49000           81
2  Carol   28         IT   52000           92
0  Alice   25         IT   45000           85
7  Henry   24      Sales   40000           70

In [64]:
#Sort performance scores from highest to lowest
df.sort_values("Performance", ascending=False)

    Name  Age Department  Salary  Performance
6  Grace   38         IT   85000           95
2  Carol   28         IT   52000           92
8  Irene   45         HR   78000           90
4    Eva   35      Sales   58000           88
9  James   31         IT   61000           86
0  Alice   25         IT   45000           85
5  Frank   29    Finance   49000           81
1  Brian   32    Finance   65000           78
3  David   41         HR   72000           74
7  Henry   24      Sales   40000           70

In [65]:
#To save the sorted result:

sorted_df = df.sort_values("Salary",ascending=False)

sorted_df

    Name  Age Department  Salary  Performance
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90
3  David   41         HR   72000           74
1  Brian   32    Finance   65000           78
9  James   31         IT   61000           86
4    Eva   35      Sales   58000           88
2  Carol   28         IT   52000           92
5  Frank   29    Finance   49000           81
0  Alice   25         IT   45000           85
7  Henry   24      Sales   40000           70

In [67]:
#Sorting by Multiple Columns
df.sort_values(["Department","Salary"])

    Name  Age Department  Salary  Performance
5  Frank   29    Finance   49000           81
1  Brian   32    Finance   65000           78
3  David   41         HR   72000           74
8  Irene   45         HR   78000           90
0  Alice   25         IT   45000           85
2  Carol   28         IT   52000           92
9  James   31         IT   61000           86
6  Grace   38         IT   85000           95
7  Henry   24      Sales   40000           70
4    Eva   35      Sales   58000           88

In [69]:
df.sort_values(["Department","Salary"], ascending=[True,False])

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
5  Frank   29    Finance   49000           81
8  Irene   45         HR   78000           90
3  David   41         HR   72000           74
6  Grace   38         IT   85000           95
9  James   31         IT   61000           86
2  Carol   28         IT   52000           92
0  Alice   25         IT   45000           85
4    Eva   35      Sales   58000           88
7  Henry   24      Sales   40000           70

In [71]:
#16. Finding the Highest and Lowest Values
#Find the highest salary

df["Salary"].max()

np.int64(85000)

In [72]:
#Find the lowest salary

df["Salary"].min()

np.int64(40000)

In [75]:
#Find the employee with the highest salary
df.loc[df["Salary"].idxmax()]

Name           Grace
Age               38
Department        IT
Salary         85000
Performance       95
Name: 6, dtype: object

In [76]:
#Find the employee with the lowest salary
df.loc[df["Salary"].idxmin()]

Name           Henry
Age               24
Department     Sales
Salary         40000
Performance       70
Name: 7, dtype: object

In [77]:
#17. Selecting the Top Records
#Suppose a manager wants the three highest-paid employees.Use "nlargest()":
df.nlargest(3,"Salary")

    Name  Age Department  Salary  Performance
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90
3  David   41         HR   72000           74

In [78]:
#To find the five highest-performing employees:
df.nlargest(5,"Performance")

    Name  Age Department  Salary  Performance
6  Grace   38         IT   85000           95
2  Carol   28         IT   52000           92
8  Irene   45         HR   78000           90
4    Eva   35      Sales   58000           88
9  James   31         IT   61000           86

In [79]:
#To find the three youngest employees:
df.nsmallest(3,"Age")

    Name  Age Department  Salary  Performance
7  Henry   24      Sales   40000           70
0  Alice   25         IT   45000           85
2  Carol   28         IT   52000           92

In [82]:
#18. Combining Filtering and Sorting
#Find employees in IT who earn more than 50,000, and list them from highest to lowest salary.»
result=df[(df["Department"]=="IT")& (df["Salary"]>50000)].sort_values(["Salary"],ascending=False)
result

    Name  Age Department  Salary  Performance
6  Grace   38         IT   85000           95
9  James   31         IT   61000           86
2  Carol   28         IT   52000           92

In [86]:
#Find employees aged 30 or older with performance scores above 80, ordered by performance.»
results=df[(df["Age"]>=30) & (df["Performance"]>80)].sort_values("Performance",ascending=False)
results

    Name  Age Department  Salary  Performance
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90
4    Eva   35      Sales   58000           88
9  James   31         IT   61000           86

In [88]:
#Guided Practical Exercises

#Exercise 1: Selecting columns
df.columns

Index(['Name', 'Age', 'Department', 'Salary', 'Performance'], dtype='str')

In [96]:
#Using the employee DataFrame, display:

#1. Names only.
df["Name"]

0    Alice
1    Brian
2    Carol
3    David
4      Eva
5    Frank
6    Grace
7    Henry
8    Irene
9    James
Name: Name, dtype: str

In [97]:
#2. Names and salaries.
df[["Name","Salary"]]

    Name  Salary
0  Alice   45000
1  Brian   65000
2  Carol   52000
3  David   72000
4    Eva   58000
5  Frank   49000
6  Grace   85000
7  Henry   40000
8  Irene   78000
9  James   61000

In [98]:
#3. Names, departments, and performance scores.
df[["Name","Department","Performance"]]

    Name Department  Performance
0  Alice         IT           85
1  Brian    Finance           78
2  Carol         IT           92
3  David         HR           74
4    Eva      Sales           88
5  Frank    Finance           81
6  Grace         IT           95
7  Henry      Sales           70
8  Irene         HR           90
9  James         IT           86

In [99]:
#4. The first four rows.
df.head(4)

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
1  Brian   32    Finance   65000           78
2  Carol   28         IT   52000           92
3  David   41         HR   72000           74

In [100]:
#5. The last three rows.
df.tail(3)

    Name  Age Department  Salary  Performance
7  Henry   24      Sales   40000           70
8  Irene   45         HR   78000           90
9  James   31         IT   61000           86

In [101]:
#Exercise 2: Single-condition filtering

#Write code to find:
#1. Employees earning more than 55,000.
df[df["Salary"]>55000]

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
3  David   41         HR   72000           74
4    Eva   35      Sales   58000           88
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90
9  James   31         IT   61000           86

In [102]:
#2. Employees aged below 30.
df[df["Age"]<30]

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
2  Carol   28         IT   52000           92
5  Frank   29    Finance   49000           81
7  Henry   24      Sales   40000           70

In [103]:
#3. Employees working in Finance.
df[df["Department"]=="Finance"]

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
5  Frank   29    Finance   49000           81

In [104]:
#4. Employees with performance scores of at least 85.
df[df["Performance"]>=85]

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
2  Carol   28         IT   52000           92
4    Eva   35      Sales   58000           88
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90
9  James   31         IT   61000           86

In [106]:
#5. Employees who do not work in HR.
df[df["Department"]!="HR"]

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
1  Brian   32    Finance   65000           78
2  Carol   28         IT   52000           92
4    Eva   35      Sales   58000           88
5  Frank   29    Finance   49000           81
6  Grace   38         IT   85000           95
7  Henry   24      Sales   40000           70
9  James   31         IT   61000           86

In [107]:
#Exercise 3: Multiple conditions

#Find:1. IT employees earning more than 50,000.
df[(df["Department"]=="IT") &(df["Salary"]>50000)]

    Name  Age Department  Salary  Performance
2  Carol   28         IT   52000           92
6  Grace   38         IT   85000           95
9  James   31         IT   61000           86

In [108]:
#2. Employees older than 30 who earn less than 70,000.
df[(df["Age"]>30) &(df["Salary"]<70000)]

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
4    Eva   35      Sales   58000           88
9  James   31         IT   61000           86

In [110]:
#3. Employees in Finance or Sales.
df[(df["Department"]=="Finance")|(df["Department"]=="Sales")]

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
4    Eva   35      Sales   58000           88
5  Frank   29    Finance   49000           81
7  Henry   24      Sales   40000           70

In [111]:
#4. Employees earning between 45,000 and 65,000.
df[df["Salary"].between(45000,65000)]

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
1  Brian   32    Finance   65000           78
2  Carol   28         IT   52000           92
4    Eva   35      Sales   58000           88
5  Frank   29    Finance   49000           81
9  James   31         IT   61000           86

In [112]:
#5. Employees whose performance is at least 85 and whose salary is at least 50,000.
df[(df["Performance"]>=85) & (df["Salary"]>=50000)]

    Name  Age Department  Salary  Performance
2  Carol   28         IT   52000           92
4    Eva   35      Sales   58000           88
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90
9  James   31         IT   61000           86

In [114]:
#Exercise 4: Sorting
#Write code to: 1. Sort salaries from lowest to highest.
df.sort_values(["Salary"])

    Name  Age Department  Salary  Performance
7  Henry   24      Sales   40000           70
0  Alice   25         IT   45000           85
5  Frank   29    Finance   49000           81
2  Carol   28         IT   52000           92
4    Eva   35      Sales   58000           88
9  James   31         IT   61000           86
1  Brian   32    Finance   65000           78
3  David   41         HR   72000           74
8  Irene   45         HR   78000           90
6  Grace   38         IT   85000           95

In [115]:
#2. Sort salaries from highest to lowest.
df.sort_values(["Salary"],ascending=False)

    Name  Age Department  Salary  Performance
6  Grace   38         IT   85000           95
8  Irene   45         HR   78000           90
3  David   41         HR   72000           74
1  Brian   32    Finance   65000           78
9  James   31         IT   61000           86
4    Eva   35      Sales   58000           88
2  Carol   28         IT   52000           92
5  Frank   29    Finance   49000           81
0  Alice   25         IT   45000           85
7  Henry   24      Sales   40000           70

In [116]:
#3. Sort employees by department.
df.sort_values(["Department"])

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
5  Frank   29    Finance   49000           81
3  David   41         HR   72000           74
8  Irene   45         HR   78000           90
0  Alice   25         IT   45000           85
2  Carol   28         IT   52000           92
6  Grace   38         IT   85000           95
9  James   31         IT   61000           86
4    Eva   35      Sales   58000           88
7  Henry   24      Sales   40000           70

In [117]:
#4. Sort employees by age from youngest to oldest.
df.sort_values(["Age"])

    Name  Age Department  Salary  Performance
7  Henry   24      Sales   40000           70
0  Alice   25         IT   45000           85
2  Carol   28         IT   52000           92
5  Frank   29    Finance   49000           81
9  James   31         IT   61000           86
1  Brian   32    Finance   65000           78
4    Eva   35      Sales   58000           88
6  Grace   38         IT   85000           95
3  David   41         HR   72000           74
8  Irene   45         HR   78000           90

In [118]:
#5. Display the three highest-performing employees.
df.nlargest(3,"Performance")

    Name  Age Department  Salary  Performance
6  Grace   38         IT   85000           95
2  Carol   28         IT   52000           92
8  Irene   45         HR   78000           90

In [119]:
#Exercise 5: Business questions
#Answer these questions using Python: 1. Who earns the highest salary?
df.loc[df["Salary"].idxmax()]

Name           Grace
Age               38
Department        IT
Salary         85000
Performance       95
Name: 6, dtype: object

In [120]:
#2. Who earns the lowest salary?
df.loc[df["Salary"].idxmin()]

Name           Henry
Age               24
Department     Sales
Salary         40000
Performance       70
Name: 7, dtype: object

In [123]:
#3. Which employees have a performance score below 80?
df[df["Performance"]<80]

    Name  Age Department  Salary  Performance
1  Brian   32    Finance   65000           78
3  David   41         HR   72000           74
7  Henry   24      Sales   40000           70

In [124]:
#4. Which employees are aged between 25 and 35?
df[df["Age"].between(25,35)]

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
1  Brian   32    Finance   65000           78
2  Carol   28         IT   52000           92
4    Eva   35      Sales   58000           88
5  Frank   29    Finance   49000           81
9  James   31         IT   61000           86

In [126]:
#5. Who are the three highest-paid employees in IT?
df_IT=df[df["Department"]=="IT"] 
df_IT

    Name  Age Department  Salary  Performance
0  Alice   25         IT   45000           85
2  Carol   28         IT   52000           92
6  Grace   38         IT   85000           95
9  James   31         IT   61000           86

In [127]:
df_IT.nlargest(3,"Salary")

    Name  Age Department  Salary  Performance
6  Grace   38         IT   85000           95
9  James   31         IT   61000           86
2  Carol   28         IT   52000           92

In [129]:
#Mini Project: Employee Data Analysis Report. You are a junior data analyst working for a company.

#The human resources manager has provided employee data and wants a report identifying salary and performance patterns.

#Use the following dataset:
data = {
    "Employee": ["Alice", "Brian", "Carol", "David", "Eva","Frank", "Grace", "Henry", "Irene", "James","Kevin", "Linda"],
    "Department": ["IT", "Finance", "IT", "HR", "Sales","Finance", "IT", "Sales", "HR", "IT","Finance", "Sales"],
    "Age": [25, 32, 28, 41, 35, 29,38, 24, 45, 31, 27, 33],
    "Salary": [45000, 65000, 52000, 72000, 58000,49000, 85000, 40000, 78000, 61000,55000, 63000],
    "Performance": [85, 78, 92, 74, 88, 81,95, 70, 90, 86, 89, 84]
}
df_employee=pd.DataFrame(data) 
df_employee

   Employee Department  Age  Salary  Performance
0     Alice         IT   25   45000           85
1     Brian    Finance   32   65000           78
2     Carol         IT   28   52000           92
3     David         HR   41   72000           74
4       Eva      Sales   35   58000           88
5     Frank    Finance   29   49000           81
6     Grace         IT   38   85000           95
7     Henry      Sales   24   40000           70
8     Irene         HR   45   78000           90
9     James         IT   31   61000           86
10    Kevin    Finance   27   55000           89
11    Linda      Sales   33   63000           84

In [130]:
#Project Task 1: Inspect the data

#Find: Total employees.
# Number of departments.
df_employee.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee     12 non-null     str
 1   Department   12 non-null     str
 2   Age          12 non-null     int64
 3   Salary       12 non-null     int64
 4   Performance  12 non-null     int64
dtypes: int64(3), str(2)
memory usage: 612.0 bytes

In [131]:
 #Average salary.
df_employee["Salary"].mean()

np.float64(60250.0)

In [132]:
#- Average performance score.
df_employee["Performance"].mean()

np.float64(84.33333333333333)

In [134]:
#Project Task 2: Analyze salaries
#Identify: The highest-paid employee.
df_employee.loc[df_employee["Salary"].idxmax()]

Employee       Grace
Department        IT
Age               38
Salary         85000
Performance       95
Name: 6, dtype: object

In [135]:
#The lowest-paid employee.
df_employee.loc[df_employee["Salary"].idxmin()]

Employee       Henry
Department     Sales
Age               24
Salary         40000
Performance       70
Name: 7, dtype: object

In [136]:
#Employees earning more than 60,000.
df_employee[df_employee["Salary"]>60000]

   Employee Department  Age  Salary  Performance
1     Brian    Finance   32   65000           78
3     David         HR   41   72000           74
6     Grace         IT   38   85000           95
8     Irene         HR   45   78000           90
9     James         IT   31   61000           86
11    Linda      Sales   33   63000           84

In [138]:
#Employees earning between 50,000 and 70,000.
df_employee[df_employee["Salary"].between(50000,70000)]

   Employee Department  Age  Salary  Performance
1     Brian    Finance   32   65000           78
2     Carol         IT   28   52000           92
4       Eva      Sales   35   58000           88
9     James         IT   31   61000           86
10    Kevin    Finance   27   55000           89
11    Linda      Sales   33   63000           84

In [140]:
#Project Task 3: Analyze departments
#Find employees who work in:- IT.
df_employee[df_employee["Department"]=="IT"]

  Employee Department  Age  Salary  Performance
0    Alice         IT   25   45000           85
2    Carol         IT   28   52000           92
6    Grace         IT   38   85000           95
9    James         IT   31   61000           86

In [141]:
#- Finance.
df_employee[df_employee["Department"]=="Finance"]

   Employee Department  Age  Salary  Performance
1     Brian    Finance   32   65000           78
5     Frank    Finance   29   49000           81
10    Kevin    Finance   27   55000           89

In [142]:
#- HR.
df_employee[df_employee["Department"]=="HR"]

  Employee Department  Age  Salary  Performance
3    David         HR   41   72000           74
8    Irene         HR   45   78000           90

In [143]:
#- Sales.
df_employee[df_employee["Department"]=="Sales"]

   Employee Department  Age  Salary  Performance
4       Eva      Sales   35   58000           88
7     Henry      Sales   24   40000           70
11    Linda      Sales   33   63000           84

In [146]:
#Then select employees working in IT or Finance.
df_employee[(df_employee["Department"]=="IT") | (df_employee["Department"]=="Finance")]

   Employee Department  Age  Salary  Performance
0     Alice         IT   25   45000           85
1     Brian    Finance   32   65000           78
2     Carol         IT   28   52000           92
5     Frank    Finance   29   49000           81
6     Grace         IT   38   85000           95
9     James         IT   31   61000           86
10    Kevin    Finance   27   55000           89

In [147]:
#Project Task 4: Analyze performance
#Identify: - Employees scoring at least 90.
df_employee[df_employee["Performance"]>=90]

  Employee Department  Age  Salary  Performance
2    Carol         IT   28   52000           92
6    Grace         IT   38   85000           95
8    Irene         HR   45   78000           90

In [148]:
#- Employees scoring below 80.
df_employee[df_employee["Performance"]<80]

  Employee Department  Age  Salary  Performance
1    Brian    Finance   32   65000           78
3    David         HR   41   72000           74
7    Henry      Sales   24   40000           70

In [149]:
#- The five highest-performing employees.
df_employee.nlargest(5,"Performance")

   Employee Department  Age  Salary  Performance
6     Grace         IT   38   85000           95
2     Carol         IT   28   52000           92
8     Irene         HR   45   78000           90
10    Kevin    Finance   27   55000           89
4       Eva      Sales   35   58000           88

In [150]:
#Employees scoring at least 85 and earning more than 55,000.
df_employee[(df_employee["Performance"]>=85) & (df_employee["Salary"]>55000)]

  Employee Department  Age  Salary  Performance
4      Eva      Sales   35   58000           88
6    Grace         IT   38   85000           95
8    Irene         HR   45   78000           90
9    James         IT   31   61000           86

In [152]:
#Project Task 5: Sort and report: Create three separate DataFrames:
#1. Employees sorted by salary from highest to lowest.
df_salary=df_employee.sort_values("Salary",ascending=False)
df_salary

   Employee Department  Age  Salary  Performance
6     Grace         IT   38   85000           95
8     Irene         HR   45   78000           90
3     David         HR   41   72000           74
1     Brian    Finance   32   65000           78
11    Linda      Sales   33   63000           84
9     James         IT   31   61000           86
4       Eva      Sales   35   58000           88
10    Kevin    Finance   27   55000           89
2     Carol         IT   28   52000           92
5     Frank    Finance   29   49000           81
0     Alice         IT   25   45000           85
7     Henry      Sales   24   40000           70

In [155]:
#2. Employees sorted by performance from highest to lowest.
df_performance=df_employee.sort_values("Performance",ascending=False)
df_performance

   Employee Department  Age  Salary  Performance
6     Grace         IT   38   85000           95
2     Carol         IT   28   52000           92
8     Irene         HR   45   78000           90
10    Kevin    Finance   27   55000           89
4       Eva      Sales   35   58000           88
9     James         IT   31   61000           86
0     Alice         IT   25   45000           85
11    Linda      Sales   33   63000           84
5     Frank    Finance   29   49000           81
1     Brian    Finance   32   65000           78
3     David         HR   41   72000           74
7     Henry      Sales   24   40000           70

In [154]:
#3. IT employees sorted by salary from highest to lowest.
df_IT=df_employee[df_employee["Department"]=="IT"]
df_IT_salary=df_IT.sort_values("Salary",ascending=False)
df_IT_salary

  Employee Department  Age  Salary  Performance
6    Grace         IT   38   85000           95
9    James         IT   31   61000           86
2    Carol         IT   28   52000           92
0    Alice         IT   25   45000           85

In [ ]:
Project Task 6: Write your findings

Write a report of 5–8 sentences explaining:

- Which employee earns the most.
    Grace who is in the IT department earns the most
- Which employees have the strongest performance scores.
    Grace has the best performance score
- Which employees meet the salary and performance conditions.
    Grace is the 
- What patterns you noticed.

In [156]:
#Homework

#Part A: Retail Sales Analysis
#Create the following DataFrame:

sales = pd.DataFrame({
    "Product": ["Laptop", "Phone", "Tablet", "Monitor","Keyboard", "Mouse", "Printer", "Speaker","Camera", "Headphones"],
    "Category": ["Electronics", "Electronics", "Electronics","Electronics", "Accessories", "Accessories","Electronics", "Accessories", "Electronics","Accessories"],
    "Price": [800, 400, 300, 250, 50,25, 180, 90, 600, 120],
    "Quantity": [3, 10, 5, 7, 20,30, 4, 12, 2, 15]
})
df_sales=pd.DataFrame(sales) 
df_sales

      Product     Category  Price  Quantity
0      Laptop  Electronics    800         3
1       Phone  Electronics    400        10
2      Tablet  Electronics    300         5
3     Monitor  Electronics    250         7
4    Keyboard  Accessories     50        20
5       Mouse  Accessories     25        30
6     Printer  Electronics    180         4
7     Speaker  Accessories     90        12
8      Camera  Electronics    600         2
9  Headphones  Accessories    120        15

In [163]:
#Task 1: Select data
#Display:- Products and prices.
df_sales[["Product","Price"]]

      Product  Price
0      Laptop    800
1       Phone    400
2      Tablet    300
3     Monitor    250
4    Keyboard     50
5       Mouse     25
6     Printer    180
7     Speaker     90
8      Camera    600
9  Headphones    120

In [164]:
# Products and quantities.
df_sales[["Product","Quantity"]]

      Product  Quantity
0      Laptop         3
1       Phone        10
2      Tablet         5
3     Monitor         7
4    Keyboard        20
5       Mouse        30
6     Printer         4
7     Speaker        12
8      Camera         2
9  Headphones        15

In [165]:
#Products, categories, and prices.
df_sales[["Product","Price"]]

      Product  Price
0      Laptop    800
1       Phone    400
2      Tablet    300
3     Monitor    250
4    Keyboard     50
5       Mouse     25
6     Printer    180
7     Speaker     90
8      Camera    600
9  Headphones    120

In [166]:
#Task 2: Filter data
#Find: 1. Products costing more than 200.
df_sales[df_sales["Price"]>200]

   Product     Category  Price  Quantity
0   Laptop  Electronics    800         3
1    Phone  Electronics    400        10
2   Tablet  Electronics    300         5
3  Monitor  Electronics    250         7
8   Camera  Electronics    600         2

In [167]:
#2. Products costing less than 100.
df_sales[df_sales["Price"]<100]

    Product     Category  Price  Quantity
4  Keyboard  Accessories     50        20
5     Mouse  Accessories     25        30
7   Speaker  Accessories     90        12

In [168]:
#3. Electronics products.
df_sales[df_sales["Category"]=="Electronics"]

   Product     Category  Price  Quantity
0   Laptop  Electronics    800         3
1    Phone  Electronics    400        10
2   Tablet  Electronics    300         5
3  Monitor  Electronics    250         7
6  Printer  Electronics    180         4
8   Camera  Electronics    600         2

In [169]:
#4. Accessories with quantities above 10.
df_sales[(df_sales["Category"]=="Accessories") &(df_sales["Quantity"]>10)]

      Product     Category  Price  Quantity
4    Keyboard  Accessories     50        20
5       Mouse  Accessories     25        30
7     Speaker  Accessories     90        12
9  Headphones  Accessories    120        15

In [170]:
#5. Products costing between 100 and 500.
df_sales[df_sales["Price"].between(100,500)]

      Product     Category  Price  Quantity
1       Phone  Electronics    400        10
2      Tablet  Electronics    300         5
3     Monitor  Electronics    250         7
6     Printer  Electronics    180         4
9  Headphones  Accessories    120        15

In [171]:
#Task 3: Sort data
#Sort: 1. Products by price from highest to lowest.
df_sales.sort_values("Price",ascending=False)

      Product     Category  Price  Quantity
0      Laptop  Electronics    800         3
8      Camera  Electronics    600         2
1       Phone  Electronics    400        10
2      Tablet  Electronics    300         5
3     Monitor  Electronics    250         7
6     Printer  Electronics    180         4
9  Headphones  Accessories    120        15
7     Speaker  Accessories     90        12
4    Keyboard  Accessories     50        20
5       Mouse  Accessories     25        30

In [172]:
#2. Products by quantity from lowest to highest.
df_sales.sort_values("Quantity")

      Product     Category  Price  Quantity
8      Camera  Electronics    600         2
0      Laptop  Electronics    800         3
6     Printer  Electronics    180         4
2      Tablet  Electronics    300         5
3     Monitor  Electronics    250         7
1       Phone  Electronics    400        10
7     Speaker  Accessories     90        12
9  Headphones  Accessories    120        15
4    Keyboard  Accessories     50        20
5       Mouse  Accessories     25        30

In [173]:
#3. Electronics products by price from highest to lowest.
Electronics=df_sales[df_sales["Category"]=="Electronics"]
Electronics.sort_values("Price",ascending=False)

   Product     Category  Price  Quantity
0   Laptop  Electronics    800         3
8   Camera  Electronics    600         2
1    Phone  Electronics    400        10
2   Tablet  Electronics    300         5
3  Monitor  Electronics    250         7
6  Printer  Electronics    180         4

In [174]:
#Task 4: Calculate sales value
df_sales["sales_value"]=df_sales["Price"]*df_sales["Quantity"]
df_sales

      Product     Category  Price  Quantity  sales_value
0      Laptop  Electronics    800         3         2400
1       Phone  Electronics    400        10         4000
2      Tablet  Electronics    300         5         1500
3     Monitor  Electronics    250         7         1750
4    Keyboard  Accessories     50        20         1000
5       Mouse  Accessories     25        30          750
6     Printer  Electronics    180         4          720
7     Speaker  Accessories     90        12         1080
8      Camera  Electronics    600         2         1200
9  Headphones  Accessories    120        15         1800

In [176]:
#find:- The product with the highest sales value.
df_sales.loc[df_sales["sales_value"].idxmax()]

Product              Phone
Category       Electronics
Price                  400
Quantity                10
sales_value           4000
Name: 1, dtype: object

In [178]:
#- The three products with the highest sales values.
df_sales.nlargest(3,"sales_value")

      Product     Category  Price  Quantity  sales_value
1       Phone  Electronics    400        10         4000
0      Laptop  Electronics    800         3         2400
9  Headphones  Accessories    120        15         1800

In [181]:
#- Products whose sales value exceeds 1,000.
df_sales[df_sales["sales_value"]>1000]

      Product     Category  Price  Quantity  sales_value
0      Laptop  Electronics    800         3         2400
1       Phone  Electronics    400        10         4000
2      Tablet  Electronics    300         5         1500
3     Monitor  Electronics    250         7         1750
7     Speaker  Accessories     90        12         1080
8      Camera  Electronics    600         2         1200
9  Headphones  Accessories    120        15         1800

In [182]:
#- The total sales value across all products.
df_sales["sales_value"].sum()

np.int64(16200)

In [183]:
#Challenge
#products either in the electronics category or have quantity greater than 15
#sort results by sales value from highest to lowest
df_sales_eq=df_sales[(df_sales["Category"]=="Electronics") | (df_sales["Quantity"]>15)]
df_sales_eq.sort_values("sales_value",ascending=False)

    Product     Category  Price  Quantity  sales_value
1     Phone  Electronics    400        10         4000
0    Laptop  Electronics    800         3         2400
3   Monitor  Electronics    250         7         1750
2    Tablet  Electronics    300         5         1500
8    Camera  Electronics    600         2         1200
4  Keyboard  Accessories     50        20         1000
5     Mouse  Accessories     25        30          750
6   Printer  Electronics    180         4          720