In [5]:
#Python data analysis
#conditional statements
score=45
if score>=50:
    print("Pass") 
else:
    print("fail")

fail

In [10]:
score=78
if score>=80:
    print('Grade A')
elif score>=70:
    print('Grade B')
elif score>=60:
    print('grade C')
elif score>=50:
    print('Grade D')
else:
    print('pass')

Grade B

In [11]:
age=25
print(age==25)
print(age>18)
print(age<18)

True
True
False

In [13]:
#LOOP
#The 'for' loop
scores=[70,85,60,90,75]
for score in scores:
    print(score)

70
85
60
90
75

In [14]:
#loop with a calculation
scores=[70,85,60,90,75]
for score in scores:
    print(score+5)

75
90
65
95
80

In [15]:
#loop with a condition
scores=[40,55,72,35,90,48]
for score in scores:
    if score>=50:
        print(score,'pass')
    else:
        print(score,'fail')

40 fail
55 pass
72 pass
35 fail
90 pass
48 fail

In [18]:
#The 'range()' function
for number in range(5):
    print(number) 
    for number in range(1,5): 
        print(number)

0
1
2
3
4
1
1
2
3
4
2
1
2
3
4
3
1
2
3
4
4
1
2
3
4

In [19]:
#The while loop
number=1
while number<=5:
    print(number)
    number=number+1

1
2
3
4
5

In [23]:
#FUNCTIONS-A re-usable block of code
def greet():
    print("welcome to python data analysis") 
    greet()

In [30]:
#Data anylysis functions
def calculate_average(numbers):
    total=sum(numbers)
    count=len(numbers)
    average=total/count
    return average

scores=[70,80,90,60,75]
average=calculate_average(scores)
print(average)

75.0

In [33]:
#PART D:Guided coding practice
#pass or fail
score=65
if score>=50:
    print('pass')
else:
    print('fail')

pass

In [39]:
#practice 2: Grade calculator
score=73
if score>=80:
    print('Grade A')
elif score>=70:
    print('Grade B')
elif score>=60:
    print('Grade C')
elif score>=50:
    print('Grade D')
else:
    print('Fail')

Grade B

In [8]:
#practice 3: analyse scores
scores=[45,67,89,34,76,90,55]
for score in scores:
    if score>=50:
        print(score,'pass')
else:
    print(score,'fail') 
#high scores
scores=[45,67,89,34,76,90,55]
print(max(scores)) 
print(min(scores))

67 pass
89 pass
76 pass
90 pass
55 pass
55 fail
90
34

In [10]:
#find high scores
scores=[45,67,89,34,76,90,55]
for score in scores:
    if score>=70:
        print(score)

89
76
90

In [55]:
#create a function
def calculate_total(price,quantity):
    return price * quantity
    print(calculate_total(500,3))

In [57]:
#MINI DATA ANALYSIS
students=['john','mary','peter','grace','david']
scores=[65,82,48,91,73] 
#variables to track
passed_count=0
failed_count=0
#looping through both lists together
for student, score in zip(students,scores):
    #determine pass/fail status
    if score>=50:
        status="pass"
        passed_count +=1
    else:
        status="fail"
        failed_count +=1
    print(f"{student:}-{score:}-{status:}") 
#determine grade
    if score>=80:
        grade='grade A'
    elif score>=70:
        grade='grade B'
    elif score>=60:
        grade='gradeC'
    elif score>=50:
        grade='gradeD'
    else:
        grade='grade F'
    print(f"{student}-{score}-{status}-{grade}")

john-65-pass
john-65-pass-gradeC
mary-82-pass
mary-82-pass-grade A
peter-48-fail
peter-48-fail-grade F
grace-91-pass
grace-91-pass-grade A
david-73-pass
david-73-pass-grade B

In [82]:
 #total number of students
print(len(students))
print(passed_count)
print(failed_count)
print(max(scores)) 
print(min(scores)) 
#calculate average
scores=[65,82,48,91,73]
total=sum(scores)
count= len(scores)
average=total/count
print(average)

5
4
1
91
48
71.8

In [99]:
#PART G-HOMEWORK
#employee salary analysis
employees=['john','mary','peter','grace','david']
salaries=[45000,65000,38000,72000,55000]
#print each employee salary
for employee,salary in zip(employees, salaries):
    print(employee,salary) 
#find the highest salary
print(max(salaries))  
#lowest salary
print(min(salaries)) 
#average salary
total=sum(salaries)
number=len(salaries)
average=total/number
print(average)

john 45000
mary 65000
peter 38000
grace 72000
david 55000
72000
38000
55000.0

In [100]:
#print employees earning more than 50000
for employee,salary in zip(employees,salaries):
    if salary >50000:
        print(employee)

mary
grace
david

In [102]:
#count how many employees earn more than 50000
for employee,salary in zip(employees,salaries):
    if salary>50000:
        salary_count=0
        salary_count +=1
        print(salary_count)

1
1
1

In [106]:
#ASSIGNMENT 2:SALES ANALYSIS
products = ["Laptop", "Phone", "Tablet", "Keyboard", "Mouse"]
sales = [120, 250, 150, 300, 450]
#print vry product and it's sales
for product, sale in zip(products,sales):
    print(f"{product}:{sale}")

Laptop:120
Phone:250
Tablet:150
Keyboard:300
Mouse:450

In [107]:
#find the highest sales value
print(max(sales))

450

In [108]:
#find the lowest sales value
print(min(sales))

120

In [109]:
#calculate total sales
print(sum(sales))

1270

In [110]:
#calculate average sales
total=sum(sales)
count-len(sales)
average=total/count
print(average)

254.0

In [111]:
#print products with sales above 200
for product, sale in zip(products,sales):
    if sale>200:
        print(product)

Phone
Keyboard
Mouse

In [114]:
#QUIZ
#PART H QUIZ

#Answer without looking at the lesson.

#1. What is an "if" statement used for?-For conditional execution

#2. What is the difference between "=" and "=="?-= assigns while ==means equal to

#3. What does "else" do? -it executes the code if the if/elif conditions were false

#4. What is a loop?-it allows a block of code to be repeated

#5. What is the difference between a "for" loop and a "while" loop?-for loop allows an operation to be repeated a 
#fixed number of times but while it is repeated when the condition is true

#6. What does "range(5)" produce?(0,5)

#7. What is a function? a block of code that can be repeated

#8. What is a parameter? it gives information to a range

#9. What does "return" do? Retuns the results

#10. Why are loops useful when working with data? to avoid the tendous work of handling data individually. 
#allows to automate repetitive actions

# NESTED IF STATMENTS
if x>10:
 print('above 10,')
 if x>20:
print('and also above 20')
else:
print('but not above 20;)

In [118]:
#nested if statements
x=26
if x>10:
    print('above 10,')
    if x>20:
        print('and also above 20!')
    else:
        print('but not above 20')

above 10,
and also above 20!

In [124]:
age=17
has_licence= False
if age>=18:
    if has_licence:
        print('you can drive')
    else:
        print('you cannot drive')
else:
    print('you are too young to drive')

you are too young to drive

In [139]:
score=50
attendance=80
submitted=True
if score>=60:
    if attendance>=80:
        if submitted:
            print('passed with good standing')
        else:
            print('passed but missed assignment')
    else:
         print('pass but low attendance')
else:
 print('fail')

fail

In [141]:
i=1
while i<6:
    print(i) 
    i+=1
    if i==3:
        break

1
2

In [3]:
%pip install numpy

Requirement already satisfied: numpy in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.5.3)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import numpy as np
print("NumPy version:",np._version_)

AttributeError: module 'numpy' has no attribute '_version_'

In [6]:
import numpy as np
numbers=np.array([10,20,30,40,50])
print(numbers) 
print(numbers*2) 
print(numbers+5) 
print(numbers/10) 
print(numbers-10)

[10 20 30 40 50]
[ 20  40  60  80 100]
[15 25 35 45 55]
[1. 2. 3. 4. 5.]
[ 0 10 20 30 40]

In [7]:
#creating different arrays
#array of integers
ages=np.array([20,25,30,35,40])
print(ages)

[20 25 30 35 40]

In [8]:
#array of decimal numbers
prices = np.array([10.5, 20.75, 15.25, 30.00])
print(prices)

[10.5  20.75 15.25 30.  ]

In [9]:
#array of zeros
zeros=np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]

In [10]:
#array of ones
ones=np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]

In [13]:
#sequence of numbers
numbers=np.arange(1,11)
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]

In [14]:
#chcking the size of an array
numbers = np.array([10, 20, 30, 40, 50])
print(len(numbers))

5

In [16]:
#array indexing
scores = np.array([65, 72, 80, 55, 90])
print(scores[0])
print(scores[1])
print(scores[4]) 
#negative indexing
print(scores[-1])

65
72
90
90

In [17]:
#Changing an array element
scores = np.array([65, 72, 80, 55, 90])
scores[3]=70
print(scores)

[65 72 80 70 90]

In [18]:
#Array slicing
scores = np.array([65, 72, 80, 55, 90])
print(scores[1:4])

[72 80 55]

In [20]:
#Mathematical operations
prices = np.array([100, 200, 300, 400])
print(prices+5)
print(prices*5)
print(prices/5)
print(prices-10)

[105 205 305 405]
[ 500 1000 1500 2000]
[20. 40. 60. 80.]
[ 90 190 290 390]

In [21]:
#Adding 2 arrays
sales_january = np.array([100, 200, 300])
sales_february = np.array([150, 250, 350])
total=sales_january+sales_february
print(total)

[250 450 650]

In [24]:
#Important Numpy statistics
#Sum
scores = np.array([60, 70, 80, 90, 100])
print(np.sum(scores)) 
print(np.mean(scores)) 
print(np.min(scores))
print(np.max(scores))

400
80.0
60
100

In [27]:
#example:students scores
scores = np.array([65, 78, 82, 55, 91, 73, 88])
print('Total:',np.sum(scores))
print('Average:',np.mean(scores))
print('Lowest:',np.min(scores))
print('Highest:',np.max(scores))

Total: 532
Average: 76.0
Lowest: 55
Highest: 91

In [66]:
#Comparing values_np can compare value in an arrray
scores = np.array([45, 67, 82, 39, 90, 55])
print(scores>50) 
#This is a boolan array
print(scores>=50)
print(scores.dtype)

[False  True  True False  True  True]
[False  True  True False  True  True]
int64

In [30]:
#Filtering data
scores = np.array([45, 67, 82, 39, 90, 55])
#use the boolean condition to select values
passed=scores[scores>=50]
print(passed)

[67 82 90 55]

In [21]:
#Two dimnsional arrays
students=['John','Mary','Peter']
subjects=['math','english','science']
#Student   math    english    science
#John       70      80         75
#Mary       85      90         88
#Peter      60      65         70
#represent the numerical part using 2D numPy array
scores=([
    [70,80,75],
    [85,90,88],
    [60,65,70]
])
    
print(np.mean(scores,axis=0)) 
print(np.mean(scores,axis=1)) 
#using a 2D NumPy array:

[71.66666667 78.33333333 77.66666667]
[75.         87.66666667 65.        ]

In [44]:
scores = np.array([
    [70, 80, 75],
    [85, 90, 88],
    [60, 65, 70]
])
print(scores.shape)  
print(scores[0,0])
print(scores[1,2])

(3, 3)
70
88

In [45]:
#calculating by column
print(np.mean(scores,axis=0))

[71.66666667 78.33333333 77.66666667]

In [46]:
#calculating by row
print(np.mean(scores,axis=1))

[75.         87.66666667 65.        ]

In [49]:
#Guided coding practice
#creat an array containing 10, 20, 30, 40, 50, 60
numbers=np.array([10, 20, 30, 40, 50, 60])
print(numbers) 
print(len(numbers))
print(np.array(numbers[0]))
print(np.array(numbers[-1]))

[10 20 30 40 50 60]
6
10
60

In [53]:
#Exrcise 2
scores = np.array([55, 67, 72, 81, 90, 45, 88, 76])
print('Total:',np.sum(scores)) 
print('Average:',np.mean(scores))
print('Highest:',np.max(scores))
print('Lowest:',np.min(scores))

Total: 574
Average: 71.75
Highest: 90
Lowest: 45

In [56]:
#Exercise 3-apply discount
prices = np.array([100, 200, 300, 400, 500])
#apply 10% discount
print('Discounted_price:',prices*0.9)

Discounted_price: [ 90. 180. 270. 360. 450.]

In [57]:
#Exercise 4-filter scores
scores = np.array([45, 55, 62, 38, 79, 91, 49, 85])
print(scores>=50)

[False  True  True False  True  True False  True]

In [9]:
#Exercise 5
#Student  maths  English  Science
import numpy as np
scores =np.array([
    [70, 80, 75],
    [85, 90, 88],
    [60, 65, 70],
    [95, 92, 90]
])
#Average score for each student
print(np.mean(scores,axis=1)) 
#Average score for each subject
print(np.mean(scores,axis=0))  
#Highest score
print(np.max(scores))
#Lowest score
print(np.min(scores))

[75.         87.66666667 65.         92.33333333]
[77.5  81.75 80.75]
95
60

In [64]:
arr = np.array([1.1, 2.1, 3.1])
newarr=arr.astype('int')
print(newarr)
print(newarr.dtype)

[1 2 3]
int64

In [68]:
arr = np.array([1, 2, 3, 4, 5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]

In [69]:
arr = np.array([1, 2, 3, 4, 5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]

In [71]:
arr = np.array([1, 2, 3, 4, 5])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]

In [1]:
x = [1, 2, 3]
y = [1, 2, 3]
print(x==y)
print(x is y)

True
False

In [28]:
#Mini Project: Sales Data Analyzer
sales = np.array([1200, 1500, 1100, 1800, 2000, 1750, 2200])
#total weekly sales
print(np.sum(sales)) 
#Average daily sales
print(np.mean(sales))
#Highest sales
print(np.max(sales))
#Lowest sales
print(np.min(sales))

11550
1650.0
2200
1100

In [39]:
#Homework

#Homework 1 — Employee Salaries

#Create an array:

salaries = np.array([
    35000,
    42000,
    50000,
    38000,
    62000,
    45000,
    70000
])

#Calculate:

#Total salaries
print(np.sum(salaries)) 
#Average salary
print(np.mean(salaries))
#Highest salary
print(np.max(salaries))
#Lowest salary
print(np.min(salaries))
#Salaries above 45,000
print(np.array(salaries>45000))
#Salaries below 40,000
print(np.array(salaries<40000))


#Homework 2 — Monthly Sales

#Create an array containing sales for 12 months:

sales = np.array([
    12000, 15000, 14000, 18000,
    21000, 19000, 22000, 25000,
    23000, 27000, 30000, 32000
])

#Find:

#Total annual sales
print(np.sum(sales))
#Average monthly sales
print(np.mean(sales))
#Highest monthly sales
print(np.max(sales))
#Lowest monthly sales
print(np.min(sales))
#Months where sales were above 20,000
print(np.array(sales>20000))

342000
48857.142857142855
70000
35000
[False False  True False  True False  True]
[ True False False  True False False False]
258000
21500.0
32000
12000
[False False False False  True False  True  True  True  True  True  True]

In [67]:
sales = np.array([
    12000, 15000, 14000, 18000,
    21000, 19000, 22000, 25000,
    23000, 27000, 30000, 32000
])
x=[False, False, False, False,  True, False,  True,  True,  True,  True,  True,  True]
newsales=sales[x]
print(newsales)

[21000 22000 25000 23000 27000 30000 32000]

In [35]:
#Part 2 — Good sales days

#Find all days where sales were greater than "1600".
import numpy as np
print(np.array(sales>1600)) 
#Part 3 — Increase sales

#Suppose the shop expects sales to increase by 10%.

#Calculate the expected sales:
print(np.array(sales*1.10)) 
#Which day had the highest sales?»
print(np.max(sales))

[False False False  True  True  True  True]
[1320. 1650. 1210. 1980. 2200. 1925. 2420.]
2200

In [45]:
#Calculate the percentage increase between the first month's sales and the last month's sales.
newarr=([11],[0])
print(newarr)

NameError: name 'diff' is not defined

In [46]:
arr=np.array(42)
print(arr)

42

In [48]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr) 
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3

In [50]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5

In [51]:
#Convert the following 1-D array with 12 elements into a 3-D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

In [53]:
#Joining arrays
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]

In [54]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]

In [55]:
#Splitting arrays
arr = np.array([1, 2, 3, 4, 5, 6])
newarr=np.array_split(arr,3) 
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [56]:
#sorting arrays-sort()
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]

In [57]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']

In [58]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]

In [59]:
#filtering array
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]

In [72]:
import pandas as pd 
print(pd_version_)

In [71]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 113.8 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.8 MB 113.8 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.8 MB 113.8 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.8 MB 113.8 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.8 MB 113.8 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.8 MB 113.8 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.8 MB 113.8 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.8 MB 113.8 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.8 MB 113.8 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.8 MB 113.8 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.8 MB 113.8 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.8 MB 113.8 kB/s eta 0:01:22
   --- ------------------------------------ 0.8/9.8 MB 108.6 kB/s eta 0:01:23
   --- ------------------------------------ 0.8/9.8 MB 108.6 kB/s eta 0:01:23
   --- ------------------------------------ 0.8/9.8 MB 108.6 kB/s eta 0:01:23
   --- ------------------------------------ 0.8/9.8 MB 108.6 kB/s eta 0:01:23
   --- ------------------------------------ 0.8/9.8 MB 108.6 kB/s eta 0:01:23
   --- ------------------------------------ 0.8/9.8 MB 108.6 kB/s eta 0:01:23
   --- ------------------------------------ 0.8/9.8 MB 108.6 kB/s eta 0:01:23
   --- ------------------------------------ 0.8/9.8 MB 108.6 kB/s eta 0:01:23
   --- ------------------------------------ 0.8/9.8 MB 108.6 kB/s eta 0:01:23
   ---- ----------------------------------- 1.0/9.8 MB 116.3 kB/s eta 0:01:16
   ---- ----------------------------------- 1.0/9.8 MB 116.3 kB/s eta 0:01:16
   ---- ----------------------------------- 1.0/9.8 MB 116.3 kB/s eta 0:01:16
   ---- ----------------------------------- 1.0/9.8 MB 116.3 kB/s eta 0:01:16
   ---- ----------------------------------- 1.0/9.8 MB 116.3 kB/s eta 0:01:16
   ---- ----------------------------------- 1.0/9.8 MB 116.3 kB/s eta 0:01:16
   ---- ----------------------------------- 1.0/9.8 MB 116.3 kB/s eta 0:01:16
   ---- ----------------------------------- 1.0/9.8 MB 116.3 kB/s eta 0:01:16
   ---- ----------------------------------- 1.0/9.8 MB 116.3 kB/s eta 0:01:16
   ----- ---------------------------------- 1.3/9.8 MB 120.8 kB/s eta 0:01:11
   ----- ---------------------------------- 1.3/9.8 MB 120.8 kB/s eta 0:01:11
   ----- ---------------------------------- 1.3/9.8 MB 120.8 kB/s eta 0:01:11
   ----- ---------------------------------- 1.3/9.8 MB 120.8 kB/s eta 0:01:11
   ----- ---------------------------------- 1.3/9.8 MB 120.8 kB/s eta 0:01:11
   ------ --------------------------------- 1.6/9.8 MB 135.9 kB/s eta 0:01:01
   ------ --------------------------------- 1.6/9.8 MB 135.9 kB/s eta 0:01:01
   ------ --------------------------------- 1.6/9.8 MB 135.9 kB/s eta 0:01:01
   ------ --------------------------------- 1.6/9.8 MB 135.9 kB/s eta 0:01:01
   ------- -------------------------------- 1.8/9.8 MB 148.8 kB/s eta 0:00:54
   ------- -------------------------------- 1.8/9.8 MB 148.8 kB/s eta 0:00:54
   ------- -------------------------------- 1.8/9.8 MB 148.8 kB/s eta 0:00:54
   ------- -------------------------------- 1.8/9.8 MB 148.8 kB/s eta 0:00:54
   -------- ------------------------------- 2.1/9.8 MB 159.9 kB/s eta 0:00:49
   -------- ------------------------------- 2.1/9.8 MB 159.9 kB/s eta 0:00:49
   -------- ------------------------------- 2.1/9.8 MB 159.9 kB/s eta 0:00:49
   -------- ------------------------------- 2.1/9.8 MB 159.9 kB/s eta 0:00:49
   --------- ------------------------------ 2.4/9.8 MB 170.5 kB/s eta 0:00:44
   --------- ------------------------------ 2.4/9.8 MB 170.5 kB/s eta 0:00:44
   --------- ------------------------------ 2.4/9.8 MB 170.5 kB/s eta 0:00:44
   --------- ------------------------------ 2.4/9.8 MB 170.5 kB/s eta 0:00:44
   --------- ------------------------------ 2.4/9.8 MB 170.5 kB/s eta 0:00:44
   ---------- ----------------------------- 2.6/9.8 MB 177.2 kB/s eta 0:00:41
   ---------- ----------------------------- 2.6/9.8 MB 177.2 kB/s eta 0:00:41
   ---------- ----------------------------- 2.6/9.8 MB 177.2 kB/s eta 0:00:41
   ---------- ----------------------------- 2.6/9.8 MB 177.2 kB/s eta 0:00:41
   ---------- ----------------------------- 2.6/9.8 MB 177.2 kB/s eta 0:00:41
   ---------- ----------------------------- 2.6/9.8 MB 177.2 kB/s eta 0:00:41
   ----------- ---------------------------- 2.9/9.8 MB 180.4 kB/s eta 0:00:39
   ----------- ---------------------------- 2.9/9.8 MB 180.4 kB/s eta 0:00:39
   ----------- ---------------------------- 2.9/9.8 MB 180.4 kB/s eta 0:00:39
   ----------- ---------------------------- 2.9/9.8 MB 180.4 kB/s eta 0:00:39
   ----------- ---------------------------- 2.9/9.8 MB 180.4 kB/s eta 0:00:39
   ----------- ---------------------------- 2.9/9.8 MB 180.4 kB/s eta 0:00:39
   ----------- ---------------------------- 2.9/9.8 MB 180.4 kB/s eta 0:00:39
   ----------- ---------------------------- 2.9/9.8 MB 180.4 kB/s eta 0:00:39
   ----------- ---------------------------- 2.9/9.8 MB 180.4 kB/s eta 0:00:39
   ------------ --------------------------- 3.1/9.8 MB 175.2 kB/s eta 0:00:38
   ------------ --------------------------- 3.1/9.8 MB 175.2 kB/s eta 0:00:38
   ------------ --------------------------- 3.1/9.8 MB 175.2 kB/s eta 0:00:38
   ------------ --------------------------- 3.1/9.8 MB 175.2 kB/s eta 0:00:38
   ------------ --------------------------- 3.1/9.8 MB 175.2 kB/s eta 0:00:38
   ------------ --------------------------- 3.1/9.8 MB 175.2 kB/s eta 0:00:38
   ------------ --------------------------- 3.1/9.8 MB 175.2 kB/s eta 0:00:38
   ------------ --------------------------- 3.1/9.8 MB 175.2 kB/s eta 0:00:38
   ------------ --------------------------- 3.1/9.8 MB 175.2 kB/s eta 0:00:38
   ------------ --------------------------- 3.1/9.8 MB 175.2 kB/s eta 0:00:38
   ------------ --------------------------- 3.1/9.8 MB 175.2 kB/s eta 0:00:38
   ------------ --------------------------- 3.1/9.8 MB 175.2 kB/s eta 0:00:38
   ------------ --------------------------- 3.1/9.8 MB 175.2 kB/s eta 0:00:38
   ------------- -------------------------- 3.4/9.8 MB 164.2 kB/s eta 0:00:39
   ------------- -------------------------- 3.4/9.8 MB 164.2 kB/s eta 0:00:39
   ------------- -------------------------- 3.4/9.8 MB 164.2 kB/s eta 0:00:39
   ------------- -------------------------- 3.4/9.8 MB 164.2 kB/s eta 0:00:39
   ------------- -------------------------- 3.4/9.8 MB 164.2 kB/s eta 0:00:39
   ------------- -------------------------- 3.4/9.8 MB 164.2 kB/s eta 0:00:39
   ------------- -------------------------- 3.4/9.8 MB 164.2 kB/s eta 0:00:39
   ------------- -------------------------- 3.4/9.8 MB 164.2 kB/s eta 0:00:39
   ------------- -------------------------- 3.4/9.8 MB 164.2 kB/s eta 0:00:39
   ------------- -------------------------- 3.4/9.8 MB 164.2 kB/s eta 0:00:39
   ------------- -------------------------- 3.4/9.8 MB 164.2 kB/s eta 0:00:39
   ------------- -------------------------- 3.4/9.8 MB 164.2 kB/s eta 0:00:39
   ------------- -------------------------- 3.4/9.8 MB 164.2 kB/s eta 0:00:39
   ------------- -------------------------- 3.4/9.8 MB 164.2 kB/s eta 0:00:39
   ------------- -------------------------- 3.4/9.8 MB 164.2 kB/s eta 0:00:39
   -------------- ------------------------- 3.7/9.8 MB 151.6 kB/s eta 0:00:41
   -------------- ------------------------- 3.7/9.8 MB 151.6 kB/s eta 0:00:41
   -------------- ------------------------- 3.7/9.8 MB 151.6 kB/s eta 0:00:41
   -------------- ------------------------- 3.7/9.8 MB 151.6 kB/s eta 0:00:41
   -------------- ------------------------- 3.7/9.8 MB 151.6 kB/s eta 0:00:41
   -------------- ------------------------- 3.7/9.8 MB 151.6 kB/s eta 0:00:41
   ---------------- ----------------------- 3.9/9.8 MB 154.3 kB/s eta 0:00:38
   ---------------- ----------------------- 3.9/9.8 MB 154.3 kB/s eta 0:00:38
   ---------------- ----------------------- 3.9/9.8 MB 154.3 kB/s eta 0:00:38
   ---------------- ----------------------- 3.9/9.8 MB 154.3 kB/s eta 0:00:38
   ---------------- ----------------------- 3.9/9.8 MB 154.3 kB/s eta 0:00:38
   ----------------- ---------------------- 4.2/9.8 MB 158.8 kB/s eta 0:00:36
   ----------------- ---------------------- 4.2/9.8 MB 158.8 kB/s eta 0:00:36
   ----------------- ---------------------- 4.2/9.8 MB 158.8 kB/s eta 0:00:36
   ----------------- ---------------------- 4.2/9.8 MB 158.8 kB/s eta 0:00:36
   ----------------- ---------------------- 4.2/9.8 MB 158.8 kB/s eta 0:00:36
   ----------------- ---------------------- 4.2/9.8 MB 158.8 kB/s eta 0:00:36
   ----------------- ---------------------- 4.2/9.8 MB 158.8 kB/s eta 0:00:36
   ----------------- ---------------------- 4.2/9.8 MB 158.8 kB/s eta 0:00:36
   ------------------ --------------------- 4.5/9.8 MB 158.6 kB/s eta 0:00:34
   ------------------ --------------------- 4.5/9.8 MB 158.6 kB/s eta 0:00:34
   ------------------ --------------------- 4.5/9.8 MB 158.6 kB/s eta 0:00:34
   ------------------ --------------------- 4.5/9.8 MB 158.6 kB/s eta 0:00:34
   ------------------ --------------------- 4.5/9.8 MB 158.6 kB/s eta 0:00:34
   ------------------- -------------------- 4.7/9.8 MB 161.1 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 161.1 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 161.1 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 161.1 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 161.1 kB/s eta 0:00:32
   ------------------- -------------------- 4.7/9.8 MB 161.1 kB/s eta 0:00:32
   -------------------- ------------------- 5.0/9.8 MB 163.4 kB/s eta 0:00:30
   -------------------- ------------------- 5.0/9.8 MB 163.4 kB/s eta 0:00:30
   -------------------- ------------------- 5.0/9.8 MB 163.4 kB/s eta 0:00:30
   -------------------- ------------------- 5.0/9.8 MB 163.4 kB/s eta 0:00:30
   -------------------- ------------------- 5.0/9.8 MB 163.4 kB/s eta 0:00:30
   -------------------- ------------------- 5.0/9.8 MB 163.4 kB/s eta 0:00:30
   -------------------- ------------------- 5.0/9.8 MB 163.4 kB/s eta 0:00:30
   --------------------- ------------------ 5.2/9.8 MB 168.2 kB/s eta 0:00:28
   --------------------- ------------------ 5.2/9.8 MB 168.2 kB/s eta 0:00:28
   --------------------- ------------------ 5.2/9.8 MB 168.2 kB/s eta 0:00:28
   --------------------- ------------------ 5.2/9.8 MB 168.2 kB/s eta 0:00:28
   --------------------- ------------------ 5.2/9.8 MB 168.2 kB/s eta 0:00:28
   --------------------- ------------------ 5.2/9.8 MB 168.2 kB/s eta 0:00:28
   --------------------- ------------------ 5.2/9.8 MB 168.2 kB/s eta 0:00:28
   --------------------- ------------------ 5.2/9.8 MB 168.2 kB/s eta 0:00:28
   --------------------- ------------------ 5.2/9.8 MB 168.2 kB/s eta 0:00:28
   --------------------- ------------------ 5.2/9.8 MB 168.2 kB/s eta 0:00:28
   ---------------------- ----------------- 5.5/9.8 MB 169.8 kB/s eta 0:00:26
   ---------------------- ----------------- 5.5/9.8 MB 169.8 kB/s eta 0:00:26
   ---------------------- ----------------- 5.5/9.8 MB 169.8 kB/s eta 0:00:26
   ---------------------- ----------------- 5.5/9.8 MB 169.8 kB/s eta 0:00:26
   ---------------------- ----------------- 5.5/9.8 MB 169.8 kB/s eta 0:00:26
   ----------------------- ---------------- 5.8/9.8 MB 172.6 kB/s eta 0:00:24
   ----------------------- ---------------- 5.8/9.8 MB 172.6 kB/s eta 0:00:24
   ----------------------- ---------------- 5.8/9.8 MB 172.6 kB/s eta 0:00:24
   ----------------------- ---------------- 5.8/9.8 MB 172.6 kB/s eta 0:00:24
   ----------------------- ---------------- 5.8/9.8 MB 172.6 kB/s eta 0:00:24
   ----------------------- ---------------- 5.8/9.8 MB 172.6 kB/s eta 0:00:24
   ----------------------- ---------------- 5.8/9.8 MB 172.6 kB/s eta 0:00:24
   ------------------------ --------------- 6.0/9.8 MB 175.8 kB/s eta 0:00:22
   ------------------------ --------------- 6.0/9.8 MB 175.8 kB/s eta 0:00:22
   ------------------------ --------------- 6.0/9.8 MB 175.8 kB/s eta 0:00:22
   ------------------------ --------------- 6.0/9.8 MB 175.8 kB/s eta 0:00:22
   ------------------------ --------------- 6.0/9.8 MB 175.8 kB/s eta 0:00:22
   ------------------------- -------------- 6.3/9.8 MB 177.9 kB/s eta 0:00:20
   ------------------------- -------------- 6.3/9.8 MB 177.9 kB/s eta 0:00:20
   ------------------------- -------------- 6.3/9.8 MB 177.9 kB/s eta 0:00:20
   ------------------------- -------------- 6.3/9.8 MB 177.9 kB/s eta 0:00:20
   ------------------------- -------------- 6.3/9.8 MB 177.9 kB/s eta 0:00:20
   ------------------------- -------------- 6.3/9.8 MB 177.9 kB/s eta 0:00:20
   ------------------------- -------------- 6.3/9.8 MB 177.9 kB/s eta 0:00:20
   ------------------------- -------------- 6.3/9.8 MB 177.9 kB/s eta 0:00:20
   -------------------------- ------------- 6.6/9.8 MB 179.6 kB/s eta 0:00:19
   -------------------------- ------------- 6.6/9.8 MB 179.6 kB/s eta 0:00:19
   -------------------------- ------------- 6.6/9.8 MB 179.6 kB/s eta 0:00:19
   -------------------------- ------------- 6.6/9.8 MB 179.6 kB/s eta 0:00:19
   -------------------------- ------------- 6.6/9.8 MB 179.6 kB/s eta 0:00:19
   -------------------------- ------------- 6.6/9.8 MB 179.6 kB/s eta 0:00:19
   --------------------------- ------------ 6.8/9.8 MB 177.8 kB/s eta 0:00:17
   --------------------------- ------------ 6.8/9.8 MB 177.8 kB/s eta 0:00:17
   --------------------------- ------------ 6.8/9.8 MB 177.8 kB/s eta 0:00:17
   --------------------------- ------------ 6.8/9.8 MB 177.8 kB/s eta 0:00:17
   --------------------------- ------------ 6.8/9.8 MB 177.8 kB/s eta 0:00:17
   --------------------------- ------------ 6.8/9.8 MB 177.8 kB/s eta 0:00:17
   --------------------------- ------------ 6.8/9.8 MB 177.8 kB/s eta 0:00:17
   ---------------------------- ----------- 7.1/9.8 MB 170.5 kB/s eta 0:00:16
   ---------------------------- ----------- 7.1/9.8 MB 170.5 kB/s eta 0:00:16
   ---------------------------- ----------- 7.1/9.8 MB 170.5 kB/s eta 0:00:16
   ---------------------------- ----------- 7.1/9.8 MB 170.5 kB/s eta 0:00:16
   ---------------------------- ----------- 7.1/9.8 MB 170.5 kB/s eta 0:00:16
   ---------------------------- ----------- 7.1/9.8 MB 170.5 kB/s eta 0:00:16
   ---------------------------- ----------- 7.1/9.8 MB 170.5 kB/s eta 0:00:16
   ----------------------------- ---------- 7.3/9.8 MB 166.5 kB/s eta 0:00:15
   ----------------------------- ---------- 7.3/9.8 MB 166.5 kB/s eta 0:00:15
   ----------------------------- ---------- 7.3/9.8 MB 166.5 kB/s eta 0:00:15
   ----------------------------- ---------- 7.3/9.8 MB 166.5 kB/s eta 0:00:15
   ----------------------------- ---------- 7.3/9.8 MB 166.5 kB/s eta 0:00:15
   ----------------------------- ---------- 7.3/9.8 MB 166.5 kB/s eta 0:00:15
   ----------------------------- ---------- 7.3/9.8 MB 166.5 kB/s eta 0:00:15
   ------------------------------- -------- 7.6/9.8 MB 162.5 kB/s eta 0:00:14
   ------------------------------- -------- 7.6/9.8 MB 162.5 kB/s eta 0:00:14
   ------------------------------- -------- 7.6/9.8 MB 162.5 kB/s eta 0:00:14
   ------------------------------- -------- 7.6/9.8 MB 162.5 kB/s eta 0:00:14
   ------------------------------- -------- 7.6/9.8 MB 162.5 kB/s eta 0:00:14
   ------------------------------- -------- 7.6/9.8 MB 162.5 kB/s eta 0:00:14
   ------------------------------- -------- 7.6/9.8 MB 162.5 kB/s eta 0:00:14
   ------------------------------- -------- 7.6/9.8 MB 162.5 kB/s eta 0:00:14
   -------------------------------- ------- 7.9/9.8 MB 163.9 kB/s eta 0:00:12
   -------------------------------- ------- 7.9/9.8 MB 163.9 kB/s eta 0:00:12
   -------------------------------- ------- 7.9/9.8 MB 163.9 kB/s eta 0:00:12
   -------------------------------- ------- 7.9/9.8 MB 163.9 kB/s eta 0:00:12
   -------------------------------- ------- 7.9/9.8 MB 163.9 kB/s eta 0:00:12
   -------------------------------- ------- 7.9/9.8 MB 163.9 kB/s eta 0:00:12
   -------------------------------- ------- 7.9/9.8 MB 163.9 kB/s eta 0:00:12
   -------------------------------- ------- 7.9/9.8 MB 163.9 kB/s eta 0:00:12
   --------------------------------- ------ 8.1/9.8 MB 169.5 kB/s eta 0:00:10
   --------------------------------- ------ 8.1/9.8 MB 169.5 kB/s eta 0:00:10
   --------------------------------- ------ 8.1/9.8 MB 169.5 kB/s eta 0:00:10
   --------------------------------- ------ 8.1/9.8 MB 169.5 kB/s eta 0:00:10
   --------------------------------- ------ 8.1/9.8 MB 169.5 kB/s eta 0:00:10
   --------------------------------- ------ 8.1/9.8 MB 169.5 kB/s eta 0:00:10
   --------------------------------- ------ 8.1/9.8 MB 169.5 kB/s eta 0:00:10
   --------------------------------- ------ 8.1/9.8 MB 169.5 kB/s eta 0:00:10
   --------------------------------- ------ 8.1/9.8 MB 169.5 kB/s eta 0:00:10
   --------------------------------- ------ 8.1/9.8 MB 169.5 kB/s eta 0:00:10
   --------------------------------- ------ 8.1/9.8 MB 169.5 kB/s eta 0:00:10
   --------------------------------- ------ 8.1/9.8 MB 169.5 kB/s eta 0:00:10
   --------------------------------- ------ 8.1/9.8 MB 169.5 kB/s eta 0:00:10
   ---------------------------------- ----- 8.4/9.8 MB 173.2 kB/s eta 0:00:09
   ---------------------------------- ----- 8.4/9.8 MB 173.2 kB/s eta 0:00:09
   ---------------------------------- ----- 8.4/9.8 MB 173.2 kB/s eta 0:00:09
   ---------------------------------- ----- 8.4/9.8 MB 173.2 kB/s eta 0:00:09
   ---------------------------------- ----- 8.4/9.8 MB 173.2 kB/s eta 0:00:09

In [2]:
#Series:one dimensional pandas data structure
import pandas as pd
scores=pd.Series([65,72,80,55,90])
print(scores)

0    65
1    72
2    80
3    55
4    90
dtype: int64

In [8]:
#Creating Series with names
scores=pd.Series([65,72,80],
                 index=['John','Mary','Peter'])
print(scores) 
print(scores['Mary'])

John     65
Mary     72
Peter    80
dtype: int64
72

In [9]:
#Data frame-2 dimensional table containing rows and columns
data={'Name':['John','Mary','Peter','Jane'],'Age':[25,30,28,35],'Department':['IT','Finance','IT','HR'],
      'Salary':[45000,55000,48000,60000]}
df=pd.DataFrame(data)
print(df)

    Name  Age Department  Salary
0   John   25         IT   45000
1   Mary   30    Finance   55000
2  Peter   28         IT   48000
3   Jane   35         HR   60000

In [10]:
df

    Name  Age Department  Salary
0   John   25         IT   45000
1   Mary   30    Finance   55000
2  Peter   28         IT   48000
3   Jane   35         HR   60000

In [15]:
#selcting a column
print(df['Name'])
print(df['Salary']) 
salaries=df['Salary'] 
print(salaries)

0     John
1     Mary
2    Peter
3     Jane
Name: Name, dtype: str
0    45000
1    55000
2    48000
3    60000
Name: Salary, dtype: int64
0    45000
1    55000
2    48000
3    60000
Name: Salary, dtype: int64

In [18]:
#selcting multiple columns
print(df[['Name','Salary']]) 
print(df[['Name','Salary','Department']])

    Name  Salary
0   John   45000
1   Mary   55000
2  Peter   48000
3   Jane   60000
    Name  Salary Department
0   John   45000         IT
1   Mary   55000    Finance
2  Peter   48000         IT
3   Jane   60000         HR

In [21]:
#selecting rows with 'iloc'-selects data based on its numerical position
print(df.iloc[0]) 
print(df.iloc[1]) 
print(df.iloc[1,3])

Name           John
Age              25
Department       IT
Salary        45000
Name: 0, dtype: object
Name             Mary
Age                30
Department    Finance
Salary          55000
Name: 1, dtype: object
55000

In [23]:
print(df.iloc[1:3]) 
print(df.iloc[[1,3]])

    Name  Age Department  Salary
1   Mary   30    Finance   55000
2  Peter   28         IT   48000
   Name  Age Department  Salary
1  Mary   30    Finance   55000
3  Jane   35         HR   60000

In [24]:
#selecting data with loc(used to select data using labels)
print(df.loc[0])

Name           John
Age              25
Department       IT
Salary        45000
Name: 0, dtype: object

In [25]:
#checking the size of dataframe
print(df.shape)

(4, 4)

In [28]:
#chcking column names
print(df.columns) 
print(df.columns.tolist())

Index(['Name', 'Age', 'Department', 'Salary'], dtype='str')
['Name', 'Age', 'Department', 'Salary']

In [30]:
#checking data types
print(df.dtypes)

Name            str
Age           int64
Department      str
Salary        int64
dtype: object

In [34]:
df.info() 
df.head(2)

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      str
 1   Age         4 non-null      int64
 2   Department  4 non-null      str
 3   Salary      4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 260.0 bytes

   Name  Age Department  Salary
0  John   25         IT   45000
1  Mary   30    Finance   55000

In [35]:
df.tail(2)

    Name  Age Department  Salary
2  Peter   28         IT   48000
3   Jane   35         HR   60000

In [37]:
#Basic statistics-can quickly summarise numrical columns
print(df.describe()) 
print(df['Salary'].mean())

             Age        Salary
count   4.000000      4.000000
mean   29.500000  52000.000000
std     4.203173   6782.329983
min    25.000000  45000.000000
25%    27.250000  47250.000000
50%    29.000000  51500.000000
75%    31.250000  56250.000000
max    35.000000  60000.000000
52000.0

In [42]:
print(df['Salary'].max()) 
print(df['Salary'].min())
print(df['Salary'].sum())

60000
45000
208000

In [44]:
#Adding a new column-eg. adding a bonus column
df['Bonus']=df['Salary']*0.10
df

    Name  Age Department  Salary   Bonus
0   John   25         IT   45000  4500.0
1   Mary   30    Finance   55000  5500.0
2  Peter   28         IT   48000  4800.0
3   Jane   35         HR   60000  6000.0

In [46]:
#creating a total compensation column
df['Total']=df['Salary']+df['Bonus']
df

    Name  Age Department  Salary   Bonus    Total
0   John   25         IT   45000  4500.0  49500.0
1   Mary   30    Finance   55000  5500.0  60500.0
2  Peter   28         IT   48000  4800.0  52800.0
3   Jane   35         HR   60000  6000.0  66000.0

In [47]:
#filtering data eg.employees whose salary is>50000
high_salary=df[df['Salary']>50000]
print(high_salary)

   Name  Age Department  Salary   Bonus    Total
1  Mary   30    Finance   55000  5500.0  60500.0
3  Jane   35         HR   60000  6000.0  66000.0

In [48]:
#filtering by age-find employees  older than 28
older_employee=df[df['Age']>28]
print(older_employee)

   Name  Age Department  Salary   Bonus    Total
1  Mary   30    Finance   55000  5500.0  60500.0
3  Jane   35         HR   60000  6000.0  66000.0

In [50]:
#filtering employees working in IT
IT_employees=df[df['Department']=='IT']
print(IT_employees)

    Name  Age Department  Salary   Bonus    Total
0   John   25         IT   45000  4500.0  49500.0
2  Peter   28         IT   48000  4800.0  52800.0

In [51]:
#sorting data eg.sort employees by salary
df.sort_values('Salary')

    Name  Age Department  Salary   Bonus    Total
0   John   25         IT   45000  4500.0  49500.0
2  Peter   28         IT   48000  4800.0  52800.0
1   Mary   30    Finance   55000  5500.0  60500.0
3   Jane   35         HR   60000  6000.0  66000.0

In [53]:
#for highest salary first
df.sort_values('Salary',ascending=False)

    Name  Age Department  Salary   Bonus    Total
3   Jane   35         HR   60000  6000.0  66000.0
1   Mary   30    Finance   55000  5500.0  60500.0
2  Peter   28         IT   48000  4800.0  52800.0
0   John   25         IT   45000  4500.0  49500.0

In [55]:
#Guided practice
#exercise 1-creat students data frame\
students={'Name':['Alex','Brian','Carol','David','Emma'],'Age':[20,22,19,24,21],'Score':[75,82,68,91,88]}
students_df=pd.DataFrame(data) 
students_df=pd.DataFrame(students)
students_df

    Name  Age  Score
0   Alex   20     75
1  Brian   22     82
2  Carol   19     68
3  David   24     91
4   Emma   21     88

In [56]:
students_df.head()

    Name  Age  Score
0   Alex   20     75
1  Brian   22     82
2  Carol   19     68
3  David   24     91
4   Emma   21     88

In [57]:
print(students_df.Name)

0     Alex
1    Brian
2    Carol
3    David
4     Emma
Name: Name, dtype: str

In [58]:
print(students_df.Score)

0    75
1    82
2    68
3    91
4    88
Name: Score, dtype: int64

In [65]:
print(students_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes
None

In [64]:
print(students_df.describe())

             Age      Score
count   5.000000   5.000000
mean   21.200000  80.800000
std     1.923538   9.418068
min    19.000000  68.000000
25%    20.000000  75.000000
50%    21.000000  82.000000
75%    22.000000  88.000000
max    24.000000  91.000000

In [70]:
#Exercise 3-add a grade column
def calculate_grade(Score):
    if Score>=80:
        return 'A'
    elif Score>=70:
        return 'B'
    elif Score>=60:
        return 'C'
    else:
        return 'D'
students_df['Grade']=students_df['Score'].apply(calculate_grade)
students_df

    Name  Age  Score Grade
0   Alex   20     75     B
1  Brian   22     82     A
2  Carol   19     68     C
3  David   24     91     A
4   Emma   21     88     A

In [14]:
#Exercise 4-filter students who scored at least 80
students={'Name':['Alex','Brian','Carol','David','Emma'],'Age':[20,22,19,24,21],'Score':[75,82,68,91,88]} 
import pandas as pd
students_df=pd.DataFrame(students) 
top_students=students_df[students_df['Score']>=80]
print(top_students)

    Name  Age  Score
1  Brian   22     82
3  David   24     91
4   Emma   21     88

In [21]:
#sort students
students_df.sort_values('Score')

    Name  Age  Score
2  Carol   19     68
0   Alex   20     75
1  Brian   22     82
4   Emma   21     88
3  David   24     91

In [20]:
 students_df.sort_values('Score',ascending=False)

    Name  Age  Score
3  David   24     91
4   Emma   21     88
1  Brian   22     82
0   Alex   20     75
2  Carol   19     68

In [22]:
#student performance analyser
data = {
    "Name": ["John", "Mary", "Peter", "Jane", "David", "Grace"],
    "Age": [20, 21, 19, 22, 20, 23],
    "Math": [75, 88, 62, 95, 70, 84],
    "English": [80, 91, 65, 89, 72, 86],
    "Science": [78, 85, 60, 92, 68, 90]
}
import pandas as pd
df=pd.DataFrame(data)
df

    Name  Age  Math  English  Science
0   John   20    75       80       78
1   Mary   21    88       91       85
2  Peter   19    62       65       60
3   Jane   22    95       89       92
4  David   20    70       72       68
5  Grace   23    84       86       90

In [23]:
#inspect dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      str
 1   Age      6 non-null      int64
 2   Math     6 non-null      int64
 3   English  6 non-null      int64
 4   Science  6 non-null      int64
dtypes: int64(4), str(1)
memory usage: 372.0 bytes

In [24]:
print(df.dtypes)

Name         str
Age        int64
Math       int64
English    int64
Science    int64
dtype: object

In [28]:
print(df.columns) 
print(df.columns.tolist)

Index(['Name', 'Age', 'Math', 'English', 'Science'], dtype='str')
<bound method IndexOpsMixin.tolist of Index(['Name', 'Age', 'Math', 'English', 'Science'], dtype='str')>

In [34]:
print('Math mean:',df['Math'].mean()) 
print('English mean:',df['English'].mean()) 
print('Science mean:',df['Science'].mean())

Math mean: 79.0
English mean: 80.5
Science mean: 78.83333333333333

In [38]:
#find the best student
df['Total']=df['Math']+df['English']+df['Science']
df

KeyError: 'Math'

In [36]:
highest_student=df.loc[df['Total'].idxmax()]
print(highest_student)

Name            Grace
Age                40
Department    Finance
Salary          72000
Bonus          7200.0
Total         79200.0
Name: 5, dtype: object

In [50]:
#highest score in each subject
print(df['English'].max())
print(df['Math'].max())
print(df['Science'].max())

91
95
92

In [51]:
print(df['English'].max(),print(df['Math'].max(),print(df['Science'].max())))

92
95 None
91 None

In [56]:
#create an average column
df['Average']=df[['Math','English','Science']].mean(axis=1) 
df

    Name  Age  Math  English  Science  Total    Average
0   John   20    75       80       78    233  77.666667
1   Mary   21    88       91       85    264  88.000000
2  Peter   19    62       65       60    187  62.333333
3   Jane   22    95       89       92    276  92.000000
4  David   20    70       72       68    210  70.000000
5  Grace   23    84       86       90    260  86.666667

In [58]:
#sort students from highest to lowest averages
print(df.sort_values('Average',ascending=False)) 
df

    Name  Age  Math  English  Science  Total    Average
3   Jane   22    95       89       92    276  92.000000
1   Mary   21    88       91       85    264  88.000000
5  Grace   23    84       86       90    260  86.666667
0   John   20    75       80       78    233  77.666667
4  David   20    70       72       68    210  70.000000
2  Peter   19    62       65       60    187  62.333333

    Name  Age  Math  English  Science  Total    Average
0   John   20    75       80       78    233  77.666667
1   Mary   21    88       91       85    264  88.000000
2  Peter   19    62       65       60    187  62.333333
3   Jane   22    95       89       92    276  92.000000
4  David   20    70       72       68    210  70.000000
5  Grace   23    84       86       90    260  86.666667

In [64]:
#filter students-whose averag is atleast 80
df[top_students]=df[df['Average']>=80]
print(df[top_students])

    Name  Age  Math  English  Science  Total    Average
1   Mary   21    88       91       85    264  88.000000
3   Jane   22    95       89       92    276  92.000000
5  Grace   23    84       86       90    260  86.666667

In [68]:
#Create a "Grade" column using the grading system:

def calculate_grade(Average):
    if Average>=80:
        return 'A'
    elif Average>=70:
        return 'B'
    elif Average>=60:
        return 'C'
    else:
        return 'D'
df['Grade']=df['Average'].apply(calculate_grade) 
df

    Name  Age  Math  English  Science  Total    Average Grade
0   John   20    75       80       78    233  77.666667     B
1   Mary   21    88       91       85    264  88.000000     A
2  Peter   19    62       65       60    187  62.333333     C
3   Jane   22    95       89       92    276  92.000000     A
4  David   20    70       72       68    210  70.000000     B
5  Grace   23    84       86       90    260  86.666667     A

In [3]:
#Homework
employees = {
    "Name": ["John", "Mary", "Peter", "Jane", "David", "Grace"],
    "Age": [25, 31, 28, 35, 29, 40],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "Finance"],
    "Salary": [45000, 52000, 48000, 65000, 50000, 72000]
}
import pandas as pd
df=pd.DataFrame(employees) 
df

    Name  Age Department  Salary
0   John   25         IT   45000
1   Mary   31         HR   52000
2  Peter   28    Finance   48000
3   Jane   35         IT   65000
4  David   29      Sales   50000
5  Grace   40    Finance   72000

In [16]:
print(df.shape)

(6, 4)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Age         6 non-null      int64
 2   Department  6 non-null      str
 3   Salary      6 non-null      int64
dtypes: int64(2), str(2)
memory usage: 324.0 bytes

In [14]:
print(df.columns) 
print(df.columns.tolist)

Index(['Name', 'Age', 'Department', 'Salary'], dtype='str')
<bound method IndexOpsMixin.tolist of Index(['Name', 'Age', 'Department', 'Salary'], dtype='str')>

In [15]:
df.describe()

             Age        Salary
count   6.000000      6.000000
mean   31.333333  55333.333333
std     5.391351  10689.558769
min    25.000000  45000.000000
25%    28.250000  48500.000000
50%    30.000000  51000.000000
75%    34.000000  61750.000000
max    40.000000  72000.000000

print(df['Salary'].mean())

In [17]:
print(df['Salary'].mean())

55333.333333333336

In [20]:
print(df['Salary'].max())
print(df['Salary'].min())
print(df['Salary'].sum())

72000
45000
332000

In [21]:
#Employees earning more than 50,000
high_salary=df[df['Salary']>50000]
print(high_salary)

    Name  Age Department  Salary
1   Mary   31         HR   52000
3   Jane   35         IT   65000
5  Grace   40    Finance   72000

In [23]:
#Employees working in IT
IT_employees=df[df['Department']=='IT']
print(IT_employees)

   Name  Age Department  Salary
0  John   25         IT   45000
3  Jane   35         IT   65000

In [24]:
#Employees older than 30
older_employees=df[df['Age']>30]
print(older_employees)

    Name  Age Department  Salary
1   Mary   31         HR   52000
3   Jane   35         IT   65000
5  Grace   40    Finance   72000

In [25]:
#Sort employees:From lowest salary to highest.
#From highest salary to lowest.
print(df.sort_values('Salary'))

    Name  Age Department  Salary
0   John   25         IT   45000
2  Peter   28    Finance   48000
4  David   29      Sales   50000
1   Mary   31         HR   52000
3   Jane   35         IT   65000
5  Grace   40    Finance   72000

In [26]:
print(df.sort_values('Salary',ascending=False))

    Name  Age Department  Salary
5  Grace   40    Finance   72000
3   Jane   35         IT   65000
1   Mary   31         HR   52000
4  David   29      Sales   50000
2  Peter   28    Finance   48000
0   John   25         IT   45000

In [28]:
#Create a "Bonus" column equal to 10% of salary
df['Bonus']=df['Salary']*0.10
df

    Name  Age Department  Salary   Bonus
0   John   25         IT   45000  4500.0
1   Mary   31         HR   52000  5200.0
2  Peter   28    Finance   48000  4800.0
3   Jane   35         IT   65000  6500.0
4  David   29      Sales   50000  5000.0
5  Grace   40    Finance   72000  7200.0

In [29]:
df['Total']=df['Salary']+df['Bonus']
df

    Name  Age Department  Salary   Bonus    Total
0   John   25         IT   45000  4500.0  49500.0
1   Mary   31         HR   52000  5200.0  57200.0
2  Peter   28    Finance   48000  4800.0  52800.0
3   Jane   35         IT   65000  6500.0  71500.0
4  David   29      Sales   50000  5000.0  55000.0
5  Grace   40    Finance   72000  7200.0  79200.0

In [34]:
#Find the employee with the highest total compensation
highest_paid_employee=df.loc[df['Total'].idxmax()]
print(highest_paid_employee)

Name            Grace
Age                40
Department    Finance
Salary          72000
Bonus          7200.0
Total         79200.0
Name: 5, dtype: object

In [ ]:
#Lesson 5