In [42]:
import numpy as np
import pandas as pd
data = {
    "Name": [" Alice", "Brian", "Alice","Carol", "David", "Eva" ],
    "Age": [25, np.nan, 25, 200, 30, 28],
    "City": ["Kigali", "kigali", "Kigali","Nairobi", "KIGALI", "Mombasa"],
    "Salary": [ 40000, 45000, 40000, np.nan, 50000, 47000]
}

df=pd.DataFrame(data)
df

     Name    Age     City   Salary
0   Alice   25.0   Kigali  40000.0
1   Brian    NaN   kigali  45000.0
2   Alice   25.0   Kigali  40000.0
3   Carol  200.0  Nairobi      NaN
4   David   30.0   KIGALI  50000.0
5     Eva   28.0  Mombasa  47000.0

In [19]:
df.head()

      Name    Age     City   Salary
0   Alice    25.0   Kigali  40000.0
1    Brian    NaN   kigali  45000.0
2    Alice   25.0   Kigali  40000.0
3    Carol  200.0  Nairobi      NaN
4    David   30.0   KIGALI  50000.0

In [20]:
df.shape

(6, 4)

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   Age     5 non-null      float64
 2   City    6 non-null      str
 3   Salary  5 non-null      float64
dtypes: float64(2), str(2)
memory usage: 324.0 bytes

In [22]:
df.describe()

              Age        Salary
count    5.000000      5.000000
mean    61.600000  44400.000000
std     77.397028   4393.176527
min     25.000000  40000.000000
25%     25.000000  40000.000000
50%     28.000000  45000.000000
75%     30.000000  47000.000000
max    200.000000  50000.000000

In [23]:
df.isnull()

    Name    Age   City  Salary
0  False  False  False   False
1  False   True  False   False
2  False  False  False   False
3  False  False  False    True
4  False  False  False   False
5  False  False  False   False

In [24]:
df.isnull().sum()

Name      0
Age       1
City      0
Salary    1
dtype: int64

In [25]:
# total number of missing cells
df.isnull().sum().sum()

np.int64(2)

In [27]:
#Calculate the percentage of missing values
missing_percentage=df.isnull().mean()*100
print(missing_percentage)

Name       0.000000
Age       16.666667
City       0.000000
Salary    16.666667
dtype: float64

In [29]:
#handling missing values
#Remove rows with missing values
df_without_missing=df.dropna()
df_without_missing

      Name   Age     City   Salary
0   Alice   25.0   Kigali  40000.0
2    Alice  25.0   Kigali  40000.0
4    David  30.0   KIGALI  50000.0
5      Eva  28.0  Mombasa  47000.0

In [35]:
#Fill missing numerical values with the mean
df_mean=df.copy()
df_mean["Age"]=df_mean["Age"].fillna(df_mean["Age"].mean())
df_mean

      Name    Age     City   Salary
0   Alice    25.0   Kigali  40000.0
1    Brian   61.6   kigali  45000.0
2    Alice   25.0   Kigali  40000.0
3    Carol  200.0  Nairobi      NaN
4    David   30.0   KIGALI  50000.0
5      Eva   28.0  Mombasa  47000.0

In [37]:
#Fill missing values with the median
df_median=df.copy()
df_median["Age"]=df_median["Age"].fillna(df_median["Age"].median()) 
df_median

      Name    Age     City   Salary
0   Alice    25.0   Kigali  40000.0
1    Brian   28.0   kigali  45000.0
2    Alice   25.0   Kigali  40000.0
3    Carol  200.0  Nairobi      NaN
4    David   30.0   KIGALI  50000.0
5      Eva   28.0  Mombasa  47000.0

In [38]:
# Fill missing text values
df_text=df.copy()
df_text["City"]=df_text["City"].fillna("unknown") 
df_text

      Name    Age     City   Salary
0   Alice    25.0   Kigali  40000.0
1    Brian    NaN   kigali  45000.0
2    Alice   25.0   Kigali  40000.0
3    Carol  200.0  Nairobi      NaN
4    David   30.0   KIGALI  50000.0
5      Eva   28.0  Mombasa  47000.0

In [48]:
df_correct=df_median.copy()
df_correct.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [46]:
df_corrected=df_mean.copy()
df_corrected.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [44]:
#Detect and remove duplicates
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [41]:
df_mean.duplicated().sum()

np.int64(0)

In [52]:
data2 = {
    "Name": [" Alice", "Brian", "Alice","Carol", "David", "Eva" ],
    "Age": [25, np.nan, 25, 200, 30, 28],
    "City": ["Kigali", "kigali","Kigali","Nairobi", "KIGALI", "Mombasa"],
    "Salary": [ 40000, 45000, 40000, np.nan, 50000, 47000]
}
upd_df=pd.DataFrame(data2)
upd_df

     Name    Age     City   Salary
0   Alice   25.0   Kigali  40000.0
1   Brian    NaN   kigali  45000.0
2   Alice   25.0   Kigali  40000.0
3   Carol  200.0  Nairobi      NaN
4   David   30.0   KIGALI  50000.0
5     Eva   28.0  Mombasa  47000.0

In [53]:
upd_df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [54]:
#Display the duplicate records:

df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [Name, Age, City, Salary]
Index: []

In [55]:
#Remove duplicate rows:

df_no_duplicates = df.drop_duplicates()

df_no_duplicates

     Name    Age     City   Salary
0   Alice   25.0   Kigali  40000.0
1   Brian    NaN   kigali  45000.0
2   Alice   25.0   Kigali  40000.0
3   Carol  200.0  Nairobi      NaN
4   David   30.0   KIGALI  50000.0
5     Eva   28.0  Mombasa  47000.0

In [56]:
#Clean text values
#Remove spaces around names
df_clean=df.copy()
df_clean["Name"]=df_clean["Name"].str.strip()
df_clean

    Name    Age     City   Salary
0  Alice   25.0   Kigali  40000.0
1  Brian    NaN   kigali  45000.0
2  Alice   25.0   Kigali  40000.0
3  Carol  200.0  Nairobi      NaN
4  David   30.0   KIGALI  50000.0
5    Eva   28.0  Mombasa  47000.0

In [57]:
#Standardize capitalization
df_clean["City"] = df_clean["City"].str.strip().str.title()

df_clean

    Name    Age     City   Salary
0  Alice   25.0   Kigali  40000.0
1  Brian    NaN   Kigali  45000.0
2  Alice   25.0   Kigali  40000.0
3  Carol  200.0  Nairobi      NaN
4  David   30.0   Kigali  50000.0
5    Eva   28.0  Mombasa  47000.0

In [58]:
df_clean.duplicated()

0    False
1    False
2     True
3    False
4    False
5    False
dtype: bool

In [59]:
#Convert text to lowercase
df_clean["City"]=df_clean["City"].str.lower()
df_clean

    Name    Age     City   Salary
0  Alice   25.0   kigali  40000.0
1  Brian    NaN   kigali  45000.0
2  Alice   25.0   kigali  40000.0
3  Carol  200.0  nairobi      NaN
4  David   30.0   kigali  50000.0
5    Eva   28.0  mombasa  47000.0

In [60]:
#Correct data types
data = {
    "Name": ["Alice", "Brian", "Carol"],
    "Salary": ["40000", "45000", "50000"]
}

employees = pd.DataFrame(data)

employees.dtypes

Name      str
Salary    str
dtype: object

In [61]:
employees["Salary"] = pd.to_numeric(
    employees["Salary"],
    errors="coerce"
)

employees.dtypes

Name        str
Salary    int64
dtype: object

In [62]:
df = df.rename(columns={
    "Name": "name",
    "Age": "age",
    "City": "city",
    "Salary": "salary"
})
df.head()

     name    age     city   salary
0   Alice   25.0   Kigali  40000.0
1   Brian    NaN   kigali  45000.0
2   Alice   25.0   Kigali  40000.0
3   Carol  200.0  Nairobi      NaN
4   David   30.0   KIGALI  50000.0

In [ ]:
#Detect invalid values

In [64]:
#Build a cleaning workflow
cleaned = pd.DataFrame({
    "Name": [" Alice ", "Brian", "Alice","Carol", "David", "Eva"],
    "Age": [25, np.nan, 25, 200, 30, 28],
    "City": [ "Kigali", "kigali", "Kigali","Nairobi", "KIGALI", "Mombasa"],
    "Salary": [40000, 45000, 40000, np.nan, 50000, 47000]
})
cleaned_df=pd.DataFrame(cleaned)
cleaned_df

      Name    Age     City   Salary
0   Alice    25.0   Kigali  40000.0
1    Brian    NaN   kigali  45000.0
2    Alice   25.0   Kigali  40000.0
3    Carol  200.0  Nairobi      NaN
4    David   30.0   KIGALI  50000.0
5      Eva   28.0  Mombasa  47000.0

In [68]:
#Step 1: Remove unnecessary spaces
cleaned_df["Name"]=cleaned_df["Name"].str.strip() 
cleaned_df

    Name    Age     City   Salary
0  Alice   25.0   Kigali  40000.0
1  Brian    NaN   kigali  45000.0
2  Alice   25.0   Kigali  40000.0
3  Carol  200.0  Nairobi      NaN
4  David   30.0   KIGALI  50000.0
5    Eva   28.0  Mombasa  47000.0

In [70]:
cleaned_df["City"]=cleaned_df["City"].str.strip().str.title()
cleaned_df

    Name    Age     City   Salary
0  Alice   25.0   Kigali  40000.0
1  Brian    NaN   Kigali  45000.0
2  Alice   25.0   Kigali  40000.0
3  Carol  200.0  Nairobi      NaN
4  David   30.0   Kigali  50000.0
5    Eva   28.0  Mombasa  47000.0

In [72]:
#Step 2: Remove exact duplicate rows
cleaned_df.duplicated()

0    False
1    False
2     True
3    False
4    False
5    False
dtype: bool

In [75]:
cleaned_df=cleaned_df.drop_duplicates() 
cleaned_df

    Name    Age     City   Salary
0  Alice   25.0   Kigali  40000.0
1  Brian    NaN   Kigali  45000.0
3  Carol  200.0  Nairobi      NaN
4  David   30.0   Kigali  50000.0
5    Eva   28.0  Mombasa  47000.0

In [77]:
#Step 3: Investigate invalid ages
cleaned_df[~cleaned_df["Age"].between(0,120)]

    Name    Age     City   Salary
1  Brian    NaN   Kigali  45000.0
3  Carol  200.0  Nairobi      NaN

In [79]:
#Step 4: Replace invalid ages with missing values
invalid_age = ~cleaned_df["Age"].between(0, 120)

cleaned_df.loc[invalid_age, "Age"] = np.nan 
cleaned_df

    Name   Age     City   Salary
0  Alice  25.0   Kigali  40000.0
1  Brian   NaN   Kigali  45000.0
3  Carol   NaN  Nairobi      NaN
4  David  30.0   Kigali  50000.0
5    Eva  28.0  Mombasa  47000.0

In [80]:
#Step 5: Fill missing ages with the median
df_median=cleaned_df.copy()
df_median["Age"]=df_median["Age"].fillna(df_median["Age"].median())
df_median

    Name   Age     City   Salary
0  Alice  25.0   Kigali  40000.0
1  Brian  28.0   Kigali  45000.0
3  Carol  28.0  Nairobi      NaN
4  David  30.0   Kigali  50000.0
5    Eva  28.0  Mombasa  47000.0

In [81]:
#missing salaries
cleaned_df["Salary"].isnull()

0    False
1    False
3     True
4    False
5    False
Name: Salary, dtype: bool

In [7]:
#Guided exercise
#missing values
import numpy as np
import pandas as pd
students ={
    "Name": ["John", "Mary", "Peter", "Jane"],
    "Score": [70, np.nan, 85, 90],
    "Age": [20, 21, np.nan, 23]
}
df_students=pd.DataFrame(students)
df_students

    Name  Score   Age
0   John   70.0  20.0
1   Mary    NaN  21.0
2  Peter   85.0   NaN
3   Jane   90.0  23.0

In [9]:
#Count missing values in each column
df_students.isnull().sum()

Name     0
Score    1
Age      1
dtype: int64

In [10]:
#Find the average score, excluding missing values
df_clean=df_students.copy()
df_students_clean=df_clean.dropna()
df_students_clean

   Name  Score   Age
0  John   70.0  20.0
3  Jane   90.0  23.0

In [15]:
#Fill the missing score with the median score
df_median=df_students.copy()
df_median['Score']=df_median['Score'].fillna(df_median['Score'].median())
df_median

    Name  Score   Age
0   John   70.0  20.0
1   Mary   85.0  21.0
2  Peter   85.0   NaN
3   Jane   90.0  23.0

In [17]:
#Fill the missing age with the median age
df_mean=df_median.copy()
df_mean['Age']=df_mean['Age'].fillna(df_mean['Age'].mean())
df_mean

    Name  Score        Age
0   John   70.0  20.000000
1   Mary   85.0  21.000000
2  Peter   85.0  21.333333
3   Jane   90.0  23.000000

In [18]:
df_clean=df_mean.copy()
df_clean

    Name  Score        Age
0   John   70.0  20.000000
1   Mary   85.0  21.000000
2  Peter   85.0  21.333333
3   Jane   90.0  23.000000

In [19]:
df_clean.isnull().sum().sum()

np.int64(0)

In [21]:
#Exercise 2: Duplicate records
customers = {
    "Name": ["Alice", "Brian", "Alice", "David"],
    "City": ["Kigali", "Nairobi", "Kigali", "Mombasa"]
}
df_customers=pd.DataFrame(customers)
df_customers

    Name     City
0  Alice   Kigali
1  Brian  Nairobi
2  Alice   Kigali
3  David  Mombasa

In [26]:
#Check for duplicates
df_customers.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

In [27]:
df_clean=df_customers.copy()
df_clean['Name']=df_clean['Name'].str.strip().str.title()
df_clean

    Name     City
0  Alice   Kigali
1  Brian  Nairobi
2  Alice   Kigali
3  David  Mombasa

In [28]:
#Count the duplicate rows
df_customers.duplicated().sum()

np.int64(1)

In [29]:
#Remove exact duplicates
df_customers_clean=df_customers.drop_duplicates()
df_customers_clean

    Name     City
0  Alice   Kigali
1  Brian  Nairobi
3  David  Mombasa

In [ ]:
#Explain why matching names alone may not prove two customer records are duplicates.
#people ca have matching names

In [ ]:
#Exercise 3: Text cleaning

cities= pd.DataFrame({ 
    "City": [" kigali ", "KIGALI", "nairobi ", "MOMBASA"]
})
#Remove unnecessary spaces.
#Standardize capitalization.
#Count how many records belong to each city.

In [38]:
cities= pd.DataFrame({ 
    "City": [" kigali ", "KIGALI", "nairobi ", "MOMBASA"]
})
df_cities=pd.DataFrame(cities)
df_cities

       City
0   kigali
1    KIGALI
2  nairobi
3   MOMBASA

In [40]:
#Remove unnecessary spaces
df_clean=df_cities.copy()
df_clean["City"]=df_clean["City"].str.strip().str.title()
df_clean

      City
0   Kigali
1   Kigali
2  Nairobi
3  Mombasa

In [44]:
#Count how many records belong to each city
df_cities["City"].value_counts()

City
 kigali     1
KIGALI      1
nairobi     1
MOMBASA     1
Name: count, dtype: int64

In [45]:
#Exercise 4: Data types

sales = pd.DataFrame({
    "Product": ["Laptop", "Phone", "Tablet"],
    "Price": ["800", "400", "invalid"]
})
df_sales=pd.DataFrame(sales)
df_sales

  Product    Price
0  Laptop      800
1   Phone      400
2  Tablet  invalid

In [46]:
#1. Inspect the data types.
df_sales.dtypes

Product    str
Price      str
dtype: object

In [53]:
#Convert "Price" to numeric
df_sales["Price"]=pd.to_numeric(df_sales["Price"], errors="coerce")
df_sales

  Product  Price
0  Laptop  800.0
1   Phone  400.0
2  Tablet    NaN

In [54]:
#Identify the resulting missing values
df_sales.isnull()

   Product  Price
0    False  False
1    False  False
2    False   True

In [55]:
#Calculate the average valid price
df_sales["Price"].mean()

np.float64(600.0)

In [ ]:
#Explain why ""invalid"" should be investigated

In [56]:
#Mini project: Clean a Customer Dataset
customers = pd.DataFrame({
    "Customer_Name": [" Alice ", "Brian", "Alice","Carol", "David", "Eva", "Frank"],
    "Age": [25, np.nan, 25, 200, 30, 28, -5],
    "City": ["Kigali", "kigali", "Kigali","Nairobi", "KIGALI", "Mombasa", " nairobi "],
    "Annual_Spending": [40000, 45000, 40000,np.nan, 50000, 47000, -100]
})
import numpy as np
import pandas as pd
df_customers=pd.DataFrame(customers) 
df_customers

  Customer_Name    Age       City  Annual_Spending
0        Alice    25.0     Kigali          40000.0
1         Brian    NaN     kigali          45000.0
2         Alice   25.0     Kigali          40000.0
3         Carol  200.0    Nairobi              NaN
4         David   30.0     KIGALI          50000.0
5           Eva   28.0    Mombasa          47000.0
6         Frank   -5.0   nairobi            -100.0

In [57]:
#Display the first rows.
df_customers.head()

  Customer_Name    Age     City  Annual_Spending
0        Alice    25.0   Kigali          40000.0
1         Brian    NaN   kigali          45000.0
2         Alice   25.0   Kigali          40000.0
3         Carol  200.0  Nairobi              NaN
4         David   30.0   KIGALI          50000.0

In [59]:
#- Check the dimensions.
df_customers.shape

(7, 4)

In [60]:
#- Inspect the data types.
df_customers.dtypes

Customer_Name          str
Age                float64
City                   str
Annual_Spending    float64
dtype: object

In [62]:
#- Count missing values.
df_customers.isnull().sum()

Customer_Name      0
Age                1
City               0
Annual_Spending    1
dtype: int64

In [64]:
#- Identify suspicious ages and spending values.
df_customers[~df_customers["Age"].between(0,120)]

  Customer_Name    Age       City  Annual_Spending
1         Brian    NaN     kigali          45000.0
3         Carol  200.0    Nairobi              NaN
6         Frank   -5.0   nairobi            -100.0

In [81]:
df_customers[df_customers["Annual_Spending"]<0]

  Customer_Name  Age       City  Annual_Spending
6         Frank -5.0   nairobi            -100.0

In [73]:
#Task 2: Standardize text

#- Remove unnecessary spaces.
#- Standardize city capitalization.

df_clean=df_customers.copy()
df_clean["Customer_Name"]=df_clean["Customer_Name"].str.strip()
df_clean["City"]=df_clean["City"].str.strip().str.title()
df_clean

  Customer_Name    Age     City  Annual_Spending
0         Alice   25.0   Kigali          40000.0
1         Brian    NaN   Kigali          45000.0
2         Alice   25.0   Kigali          40000.0
3         Carol  200.0  Nairobi              NaN
4         David   30.0   Kigali          50000.0
5           Eva   28.0  Mombasa          47000.0
6         Frank   -5.0  Nairobi           -100.0

In [74]:
#Task 3: Remove duplicates

#Remove exact duplicate rows, and explain which fields you used to identify duplicates.
df_clean.duplicated()

0    False
1    False
2     True
3    False
4    False
5    False
6    False
dtype: bool

In [75]:
#row 2 is the duplicate
df_cleaned=df_clean.drop_duplicates()
df_cleaned

  Customer_Name    Age     City  Annual_Spending
0         Alice   25.0   Kigali          40000.0
1         Brian    NaN   Kigali          45000.0
3         Carol  200.0  Nairobi              NaN
4         David   30.0   Kigali          50000.0
5           Eva   28.0  Mombasa          47000.0
6         Frank   -5.0  Nairobi           -100.0

In [77]:
#Task 4: Validate numerical values-
#For this exercise, treat ages outside 0–120 and negative spending as invalid. 
#Replace these invalid values with missing values, but do not delete records automatically.
df_valid=df_cleaned.copy()
df_valid[~df_valid["Age"].between(0,120)]

  Customer_Name    Age     City  Annual_Spending
1         Brian    NaN   Kigali          45000.0
3         Carol  200.0  Nairobi              NaN
6         Frank   -5.0  Nairobi           -100.0

In [84]:
valid_age=df_valid[df_valid["Age"].between(0,120)]
valid_age

  Customer_Name   Age     City  Annual_Spending
0         Alice  25.0   Kigali          40000.0
4         David  30.0   Kigali          50000.0
5           Eva  28.0  Mombasa          47000.0

In [82]:
df_valid[df_valid["Annual_Spending"]<0]

  Customer_Name  Age     City  Annual_Spending
6         Frank -5.0  Nairobi           -100.0

In [85]:
valid_Spending=df_valid[df_valid["Annual_Spending"]>=0]
valid_Spending

  Customer_Name   Age     City  Annual_Spending
0         Alice  25.0   Kigali          40000.0
1         Brian   NaN   Kigali          45000.0
4         David  30.0   Kigali          50000.0
5           Eva  28.0  Mombasa          47000.0

In [ ]:
invalid_age=~df_clean[df_clean["Age"].between(0,120)]
cleaner_data=df_cleaned.copy()
clean

In [90]:
invalid_age = ~df_cleaned["Age"].between(0, 120)

df_cleaned.loc[invalid_age, "Age"] = np.nan
df_cleaned

  Customer_Name   Age     City  Annual_Spending
0         Alice  25.0   Kigali          40000.0
1         Brian   NaN   Kigali          45000.0
3         Carol   NaN  Nairobi              NaN
4         David  30.0   Kigali          50000.0
5           Eva  28.0  Mombasa          47000.0
6         Frank   NaN  Nairobi           -100.0

In [93]:
invalid_Annual_Spending=df_cleaned["Annual_Spending"]<0
df_cleaned.loc[invalid_Annual_Spending, "Annual_Spending"]=np.nan
df_cleaned

  Customer_Name   Age     City  Annual_Spending
0         Alice  25.0   Kigali          40000.0
1         Brian   NaN   Kigali          45000.0
3         Carol   NaN  Nairobi              NaN
4         David  30.0   Kigali          50000.0
5           Eva  28.0  Mombasa          47000.0
6         Frank   NaN  Nairobi              NaN

In [100]:
#Task 5: Handle missing values

#Decide how to handle missing ages.
#replace missing ages with madian
df_nomissing=df_cleaned.copy()
df_nomissing["Age"]=df_nomissing["Age"].fillna(df_nomissing["Age"].median())
df=df_nomissing 
df

  Customer_Name   Age     City  Annual_Spending
0         Alice  25.0   Kigali          40000.0
1         Brian  28.0   Kigali          45000.0
3         Carol  28.0  Nairobi              NaN
4         David  30.0   Kigali          50000.0
5           Eva  28.0  Mombasa          47000.0
6         Frank  28.0  Nairobi              NaN

In [101]:
# Decide how to handle missing spending values.
df["Annual_Spending"]=df["Annual_Spending"].fillna(df["Annual_Spending"].mean())
df

  Customer_Name   Age     City  Annual_Spending
0         Alice  25.0   Kigali          40000.0
1         Brian  28.0   Kigali          45000.0
3         Carol  28.0  Nairobi          45500.0
4         David  30.0   Kigali          50000.0
5           Eva  28.0  Mombasa          47000.0
6         Frank  28.0  Nairobi          45500.0

In [102]:
#Task 6: Validate the final dataset

#Display the cleaned data and count remaining missing values.
df.isnull().sum().sum()

np.int64(0)

In [104]:
#Task 7: Export the result

#Save your cleaned dataset:
df.to_csv("customers_data.csv",index=False)

In [105]:
#Homework
#Part A: Employee data cleaning

#Create the following dataset:

employees = pd.DataFrame({
    "Name": [" John ", "Mary", "Peter","Mary", "David", "Grace"],
    "Age": [25, 31, 28, 31, 150, -2],
    "Department": ["IT", "HR", "Finance", "HR", "IT", " finance "],
    "Salary": ["45000", "52000", "invalid","52000", "65000", "-1000"]
})
#Complete these tasks:


import numpy as np
import pandas as pd
df_employees=pd.DataFrame(employees)
df_employees

     Name  Age Department   Salary
0   John    25         IT    45000
1    Mary   31         HR    52000
2   Peter   28    Finance  invalid
3    Mary   31         HR    52000
4   David  150         IT    65000
5   Grace   -2   finance     -1000

In [106]:
#1. Inspect the dataset.
df_employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Age         6 non-null      int64
 2   Department  6 non-null      str
 3   Salary      6 non-null      str
dtypes: int64(1), str(3)
memory usage: 324.0 bytes

In [107]:
df_employees.columns

Index(['Name', 'Age', 'Department', 'Salary'], dtype='str')

In [108]:
df_employees.shape

(6, 4)

In [109]:
df_employees.dtypes

Name            str
Age           int64
Department      str
Salary          str
dtype: object

In [111]:
df_employees.describe()

              Age
count    6.000000
mean    43.833333
std     53.491744
min     -2.000000
25%     25.750000
50%     29.500000
75%     31.000000
max    150.000000

In [112]:
#2. Find duplicate records.
df_employees.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

In [125]:
#3. Remove unnecessary spaces from names and departments.
#4. Standardize department capitalization.
df_clean=df_employees.copy()
df_clean["Name"]=df_clean["Name"].str.strip().str.title()
df_clean["Department"]=df_clean["Department"].str.strip().str.upper()
df_clean

    Name  Age Department   Salary
0   John   25         IT    45000
1   Mary   31         HR    52000
2  Peter   28    FINANCE  invalid
3   Mary   31         HR    52000
4  David  150         IT    65000
5  Grace   -2    FINANCE    -1000

In [121]:
#4. Standardize department capitalization.
df_employees["Department"].str.strip().str.upper()
df_employees

     Name  Age Department   Salary
0   John    25         IT    45000
1    Mary   31         HR    52000
2   Peter   28    Finance  invalid
3    Mary   31         HR    52000
4   David  150         IT    65000
5   Grace   -2   finance     -1000

In [129]:
#5. Convert salary to numeric.
df_clean["Salary"]=pd.to_numeric(df_clean["Salary"],errors="coerce")
df_clean

    Name  Age Department   Salary
0   John   25         IT  45000.0
1   Mary   31         HR  52000.0
2  Peter   28    FINANCE      NaN
3   Mary   31         HR  52000.0
4  David  150         IT  65000.0
5  Grace   -2    FINANCE  -1000.0

In [130]:
#6. Identify missing salary values created by conversion.
df_clean["Salary"].isnull()

0    False
1    False
2     True
3    False
4    False
5    False
Name: Salary, dtype: bool

In [134]:
#7. Identify invalid ages and negative salaries.
df_invalid=df_clean.copy()
df_invalid=df_invalid[~df_invalid["Age"].between(1,120)]
df_invalid

    Name  Age Department   Salary
4  David  150         IT  65000.0
5  Grace   -2    FINANCE  -1000.0

In [135]:
#negative  salaries
invalid_salaries=df_clean.copy()
invalid_salaries=invalid_salaries[invalid_salaries["Salary"]<0]
invalid_salaries

    Name  Age Department  Salary
5  Grace   -2    FINANCE -1000.0

In [136]:
cleaned_df=df_clean.copy()
cleaned_df=cleaned_df[cleaned_df["Age"].between(0,120)]
cleaned_df=cleaned_df[cleaned_df["Salary"]>=0]
cleaned_df

   Name  Age Department   Salary
0  John   25         IT  45000.0
1  Mary   31         HR  52000.0
3  Mary   31         HR  52000.0

In [ ]:
#8. Explain how you would handle invalid records.
#First I would invstigate the cause of invalidity and if the correct data can be obtained,
#I will rplace the invalid records with the correct one.If the correct record cannot b obtained,depending on the
#type of research and the data impliction, I would either drop the invalid record, treat it as missing rcord or 
#use the mean or the median.

In [137]:
#9. Save the cleaned dataset as "clean_employees.csv".
cleaned_df.to_csv("clean_employees.csv",index=False)